### ISSUE TITLE
Better Sample Track support

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1471]
This is a placeholder to consolidate Sample Track related issues and requests. If a new Sample Track bug is reported on the tracker, close it out and mark it as a duplicate of this bug, (#1471)

![screen shot 2014-12-20 at 10 15 30 am](https://cloud.githubusercontent.com/assets/6345473/5515264/2dec11f8-8831-11e4-9d86-98329c07636d.png)

---

**Basic Functionality:**
- [x] Pan Sample Track #1080 #1360 (Closed via #1481)
- [x] Play Sample Track mid-song #131 #2596 (Closed via #3133)
- [x] FX Mixer Support #133 #1360 #2619 (Closed via #3866)
- [x] FadeButton LED/Track Indicator #1360
- [ ] FX Mixer Preset Support #1816
- [ ] Drag and drop sample support
   - [x] Drag samples to new TCO segments #3228 (Closed via #5043)
   - [x] Drag and drop samples between tracks #881
   - [x] Easier access to built-in samples, probably through drag/drop #4221
   - [ ] Drag samples in from other applications 
- [ ] Fix SampleTrack size in BBEditor #4224

**Enhanced Functionality:**
- [ ] Better performance through mapped sample files #4015
- [ ] Sample caching (Work in progress: #6390)
- [ ] Sample Track beat-mapping support #756
- [ ] Static tempo for Sample Track #1161
- [x] Resize Sample Track from both sides #756, #701 (Closed via #3487)
- [x] Sample cutting [forum/#3330](https://lmms.io/forum/viewtopic.php?f=15&t=3330) (Closed via #4998)
- [ ] More AFP-plugin-like features #858
- [x] Better wave-editing capabilities #495 (Supported via the SlicerT plugin in #6857 rather than built into Sample Tracks)
- [ ] Fading/crossfading (Work in progress: #5616)
- [ ] Sample Track recording ~~#908~~ ~~#1360~~ #3943 (started in #3947, continued by ~#4531~ #4994)
    - [ ] Audio-input selection #1360 [Milestone: 1.3+]
- [ ] Sample distinction via naming
- [ ] Allow visualizing both stereo channels #4598

**Professional-Grade Enhancments**
- [ ] Pitch and pitch range support [#1471](https://github.com/LMMS/lmms/issues/1471#issuecomment-104350718)
- [ ] BPM Mapping (mentioned below in this thread)
- [x] Colorization support #1360 (Closed via #5573)

**Bugs:**
- [x] Sample not in sync with waveform https://github.com/LMMS/lmms/issues/1471#issuecomment-118354809 (Closed via #3133)
- [x] Sample gets cut off prematurely  #2778, https://github.com/LMMS/lmms/issues/1471#issuecomment-118354809 (Fixed in #4991 or #5226)

**Related:**
- (none reported yet)

**Comment by liftarn** [comment]
Would it be possible to do drag and drop of samples between tracks?

**Comment by badosu** [comment]
I just don't understand why we have track samples if an AudioFileProcessor is much more versatile and integrates better with the LMMS environment.

Is there any advantage in using a Sample track compared to AudioFileProcessor?

**Comment by tresf** [comment]
> Is there any advantage in using a Sample track compared to AudioFileProcessor?

Most people are already using AFP.  I think the main advantage is multiple samples per track, which AFP doesn't really allow.

-Tres

**Comment by badosu** [comment]
It's difficult, because today the only kind of sample treatment that I am aware of can be done natively by lmms is using AFP, things like slicing etc...

But these features are somewhat orthogonal with how AFP is designed today.

Maybe Sample Tracks will be useful in the future if we are able to add these features?

**Comment by tresf** [comment]
> It's difficult, because today the only kind of sample treatment I am aware of that can be done natively by lmms is using AFP, things like slicing etc...

Right... 

> Maybe Sample Tracks will be useful in the future if we are able to add these features?

I tend to agree with your original statement... Reuse AFP at all costs. (or subclass it).  But that's a very high-level hypothetical wish.  I can't speak to the complexity of the implementation.

One thing is that AFP has some features which would almost certainly have to be disabled for SampleTrack, such as loop points, and probably most of the envelope features.

**Comment by badosu** [comment]
Yeah, sorry for digressing a little, I just wanted to understand what is the role of Sample Track on LMMS today. This is relevant to plan how to enhance it.

**Comment by tresf** [comment]
> Yeah, sorry for digressing a little, I just wanted to understand what is the role of Sample Track on LMMS today. This is relevant to plan how to enhance it.

Absolutely.  I don't see any digressing here.  Part of solving a problem is understanding it, and I'm a huge proponent of that! :+1: 

When it comes to solving this problem, I think we'll be faced with two approaches (improve SampleTrack versus extend AFP).  Since basic wave editing is critical to sample track implementations in all DAWs, I would say AFP if the place to be. :)

**Comment by Sti2nd** [comment]
> Is there any advantage in using a Sample track compared to AudioFileProcessor?

Of course it is, they are fundamental different, you don't use a Sampletrack for a drum kick, and you don't use AFP for a one minute long audio file.

**Comment by tresf** [comment]
> Of course it is, they are fundamental different, you don't use a Sampletrack for a drum kick, and you don't use AFP for a one minute long audio file.

Speak for yourself please. :wink:

**Comment by liftarn** [comment]
I often use sample tracks for beats I have made earlier. It is a bit tedious to copy one beat across an entire track. I tried to use AudioFileProcessor for it, both in piano roll and the beat editor, but I couldn't get them to line up correctly.

**Comment by Umcaruje** [comment]
Also Sample Tracks can be used to consolidate(resample) your instruments. You take and Render your CPU-heavy instrument, and import it back as a sample track, thus reducing CPU usage. It's be wierd to use AFP for that.

**Comment by tresf** [comment]
> You take and Render your CPU-heavy instrument, and import it back as a sample track, thus reducing CPU usage. It's be wierd to use AFP for that.

Well, we're talking functionally.  AFP can do exactly as you are describing, it just requires the use of a Piano Roll and is limited to a single sample per track.  Yes, it is weird, but what you are describing is how I've chosen to use long samples anyway.  Without the standard FX assignment, you can't EQ or add compression to lengthy recordings.

I think what you are referring to is the Song Editor's UI portion of AFP.  Without question that is "weird" to use, but many of us are already doing it today since there is no equivalent functionality in the software. :)

![image](https://cloud.githubusercontent.com/assets/6345473/5681490/f284624e-97e6-11e4-9465-40642513137f.png)

**Comment by Umcaruje** [comment]
>I think what you are referring to is the Song Editor's UI portion of AFP. Without question that is "weird" to use, but many of us are already doing it today since there is no equivalent functionality in the software. :)

Because of these limits I use AFP too, but @badosu asked about the point of Sample Tracks, so I said what they can be used for :) I hope they will get more features soon and become worthy using, but I agree that in their current state they are mostly useless.

**Comment by tresf** [comment]
>  but @badosu asked about the point of Sample Tracks

Not trying to nitpick here, but he asked in comparison to AFP.  You're example works fine with AFP, minus the weirdness. :turtle: 

-Tres

**Comment by Sti2nd** [comment]
Apparently Tres' description of how he uses AFP is also a workaround for the lack of functionality in Sampletracks. It would be easier to understand the difference if you didn't explain how you potentially could use AFP for the same as a Sampletrack with more effort, Tres :) I get that as of now there isn't really so much benefits of using a Sampletrack, and thus AFP integrates better as of today badosu, but if the Sampletrack had all features like described in the initial comment, it would be the one to use for longer samples and maybe one time effects.

**Comment by tresf** [comment]
> It would be easier to understand the difference if you didn't explain how you potentially could use AFP for the same as a Sampletrack with more effort, Tres :)

6 now, have a dozen later, I'm not sure what you are driving at.  A feature is a feature.  Mind that I also examined the sample track code and tried to fix a few bugs.  I'm not firing off a wish list here, this is deductive problem solving and the question "WHY NOT USE AFP INSTEAD" is completely valid.  non one is saying I want AFP functionality in the GUI, so don't think we're trying to candy coat something that doesn't work as intended as a solution for something is broken.

Instead the discussion was a fundamental one about why a completely second plugin is necessary if one can do both functions.  Graphically and functionally, we all want a real sample track.  No one is trying to cloud that, I just think you're reading a bit into our conversations and trying to prevent a derailment that won't happen. :smiley:

**Comment by Sti2nd** [comment]
Oh, ok. You were talking code. Yes you could use the same code I suppose, I thought @badosu didn't understand why one would have two different instances/plugins/tracks playing audio files, that is what I tried to answer.

**Comment by tresf** [comment]
Right... He's trying to tackle it from a coding perspective.  Something like shortening the sample length for example has already been handled in AFP.  So has the chaining of FX effects, pitch support, FX channel assignment, etc.  When fixing SampleTrack one must stop and ask "how much effort is worth it when we have most of this code already written".

I would like to see AFP operate in dual mode for this, but that's a tall request to make when I have no intentions of coding it... :smirk:

**Comment by Umcaruje** [comment]
This should be turned into a [task list](https://github.com/blog/1375%0A-task-lists-in-gfm-issues-pulls-comments) so its easier to mark fixed issues.

**Comment by Reaper10** [comment]
What about change the name of the track?

**Comment by tresf** [comment]
> What about change the name of the track?

![image](https://cloud.githubusercontent.com/assets/6345473/6455351/fd8ca382-c120-11e4-9213-1d492d63f9b0.png)

Do you mean the individual segments?

**Comment by Reaper10** [comment]
form sample track to audio track.

**Comment by tresf** [comment]
That's just cosmetic.  We could change that any time, but at this point I don't think it adds much value.  We have some conversations in other threads about different names for existing components (Song Editor vs. Sequencer, BBEditor vs. Step Editor, etc).  Better names is on our radar, but I'm intentionally leaving it off of this bug report. :+1:

**Comment by Reaper10** [comment]
For singer LMMS could use a Deser

**Comment by liftarn** [comment]
I saw https://www.youtube.com/watch?v=EPkd-xUTDrU and the function to loop a sample would be very nice to have for pre-recorded drums. It would probably not be enough to just start playing it again after the first iteration is done since they will drift over time so some kind of tempo matching would be needed.

**Comment by dednikko** [comment]
This is already easily doable in LMMS.  You load the sample into an Audio
File Processor that is in a Beat/Bass line pattern. You can use the A.F.P.
To trim start and stop down to the sample,  and then use pitch control for
minute playback/pitch adjustments.

Then just drag that B/B track out on the song editor wherever you need it
looped.

**Comment by Reaper10** [comment]
You should add a open in AFP right click option to the Sample Track witch will auto load a new AFP with the clip in it.

**Comment by liftarn** [comment]
Using AFP to loop a beat in the Beat/Bass editor would be very nice. Too bad it is near impossible to get a smooth loop. Either it is too long and you get double beats where it overlaps or it's too short so you get a silence at loop points.

**Comment by badosu** [comment]
Ideally we could use a looper like Luppp embedded on LMMS: http://openavproductions.com/luppp/.

This requires lv2 support though, which is something I am stufying to implement.

**Comment by musikBear** [comment]
@badosu -those are great links. I will  add them  to wiki's *useful-resources*

**Comment by badosu** [comment]
> Should we add them to wiki's useful-resources

No until LMMS has lv2 support.

> eg, do they work as 'stand-alone' 

Some of them do, some not. If you use Jack you can plug Carla and make them work with lmms, see: http://kxstudio.sourceforge.net/Applications:Catia

**Comment by Sti2nd** [comment]
#linuxonly

**Comment by badosu** [comment]
@Sti2nd Not really, LV2 is a OS agnostic plugin interface, in contrary of VST.

Plugin authors need to care about which OS their users are using though, but LV2 does not get in the way for this.

**Comment by Sti2nd** [comment]
Wow, cool! I was speaking of Carla, cause that is Linux only, right?

**Comment by tresf** [comment]
> Wow, cool! I was speaking of Carla, cause that is Linux only, right?

Well... We haven't tried porting it to Windows or Mac yet.  The LV2 on Windows conversation is no different than the LADSPA on Windows conversation... or perhaps the ZynAddSubFX on Windows conversation... If we compile and bundle them as part of our software (with all dependencies included), then they'll most likely work.  Some OS-specific hacks may be required, but there's nothing limiting us except effort. :+1: 

-Tres

**Comment by badosu** [comment]
@StakeoutPunch As far as I know Carla works on OSX, Windows and Linux.

**Comment by Sti2nd** [comment]
> If it integrates well with LMMS is another story though

It is already integrated? Oh, well, what do I know :) You tagged the wrong person btw :warning:

**Comment by badosu** [comment]
@Sti2nd sorry about the tagging.

About the integration it allegedly has for Linux, but I never actually were able to use it. Some days ago someone on #lmms was trying to use Carla on windows to integrate with lmms but I don't know if the person was sucessful.

**Comment by Sti2nd** [comment]
That isn't the same, though? Connecting the Windows version of Carla to the Windows version of LMMS will not be an integrated plugin? I would believe one would compile LMMS on Linux for Windows as usual :thought_balloon:

**Comment by badosu** [comment]
Yep, not the same thing as we have somewhat a tighter integrations level. There should not exist any reason for it to not be ported to Windows easily though.

**Comment by mikobuntu** [comment]
@Sti2nd Carla has to be installed natively on your linux box, Carla-rack is only a bridge from LMMS to Carla. I think FalkTX plans to someday in the future port to windows tho.

**Comment by tresf** [comment]
Carla convo: https://github.com/LMMS/lmms/pull/1155#issuecomment-55299399

**Comment by badosu** [comment]
@tresf Thanks for the reference!

**Comment by Reaper10** [comment]
You should add a open in AFP in song editor or open in AFP in B&B  editor right click options to the Sample Track witch will auto load it into a new AFP in the song editor or open it into a new AFP in B&B editor.

**Comment by Reaper10** [comment]
You should add a clone this tracks routing option in the Sample Track gear menu witch will make a new blank track but, it'll keep all of the mixer and input routing setup in the new track. This will make it easier to make comp tracks.

**Comment by musikBear** [comment]
One thing thats not been mentioned at all, is *naming*
For almost the first time i looked at Sample Track, not just for test reason, but actual usage :p. I had 7 smallish pieces of wave, and i was rather annoyed as i found out, that there is no way to 'mark' these fragments, so they are easy to recognize,  and re-use in other parts of the piece. 
* Naming
a.o.
* color-change 
would be a huge help in that situation.
One thing i realized as i was working with Sample Track, was the very significant difference from AFP. Sample Track has the benefit of being able to use *many* **different** wave-samples with one and the same FX-train. To accomplish *that* with AFP, all FX's would have to be duplicated on *each* of the AFP's -A **huge** overhead!
This significants, is something that should be remembered, when Sample Track is refurbished !
Naming/ color coding, is however missing now.

**Comment by Reaper10** [comment]
Sample Track Routing Box

![sample track routing box](https://cloud.githubusercontent.com/assets/8137561/7106987/c4ee0b4c-e119-11e4-9929-5ef4506e0ae3.png)

**Comment by tresf** [comment]
@musikBear, added `Sample distinction via naming / color coding`.

**Comment by Reaper10** [comment]
LMMS could use Punch Recording
Punch Recording pro tools
https://www.youtube.com/watch?v=8U-CGDNXs3E

**Comment by tresf** [comment]
> LMMS could use Punch Recording
> Punch Recording pro tools
> https://www.youtube.com/watch?v=8U-CGDNXs3E

How about we set our sites on simply recording for now (something we have no support for currently).  We aren't aren't on the same level as pro-tools so please practice discretion when posting these things.  Your request is the equivalent of asking for a faster elevator in a one story building.

**Comment by Reaper10** [comment]
ok sorry that for latter it would be nice thi

**Comment by Reaper10** [comment]
The sample track should be able open and use mp3 files in it.

**Comment by Reaper10** [comment]
#1977

**Comment by tresf** [comment]
@Reaper10 MP3 support violates the GPL license.  Start offering fixes and not wish lists please.

**Comment by Wallacoloo** [comment]
@tresf have the LMMS developers already considered using LAME for mp3 decoding? (despite the name, it can decode as well as encode). LAME is [licensed](http://lame.sourceforge.net/license.txt) under LGPL.

**Comment by tresf** [comment]
@Wallacoloo, probably worth starting a new topic over.  I know the US, Europe and Japan historically have had some issues with the library but from a pure licensing perspective, you appear to be correct, we should be able to use it.

I know the users would be largely in support of MP3 support, so this would be a very nice feature indeed.

**Comment by musikBear** [comment]
Perhaps a look at http://mp3licensing.com/royalty/
 Frauenhofer-institute is not nice to do battles with..
How many weekly dl right now.. 5000.. ?   -> $16250 .... pr WEEK !
-And that is with  Frauenhofers lowest rates (software 2.5..5) for encoding

**Comment by curlymorphic** [comment]
I feel that mp3 support is overdue, but we must be careful with this.

Does lmms need to be able to encode as well as decode? im unsure of the licence requirements to just read an mp3. 

Users could still encode there creations in  3rd party software, but would be able to use mp3 as samples.

**Comment by tresf** [comment]
@musikBear if we did mp3, I believe it would be a reverse-engineered open source library, not the official Frauenhofer one.

**Comment by tresf** [comment]
@curlymorphic we would have tremendous value for both cases.  Decode for importing samples, vocals, etc.  Import for exporting (as an alternative to ogg).

**Comment by curlymorphic** [comment]
I can see very good use cases for both myself, but was wondering if it helped with legal issues. 

I think we need to tread careful on this one. I know many projects do use reverse-engineered open source libraries, But we are larger than most of them, so more likely to be seen.

**Comment by liftarn** [comment]
It's a moot point since patents required to implement MP3 expired in most countries by December 2012, 21 years after the publication of ISO CD 11172. An exception is the United States where patents filed for anything disclosed in ISO CD 11172 a year or more after its publication are questionable. If only the known MP3 patents filed by December 1992 are considered, then MP3 decoding may be patent-free in the US by September 2015 when U.S. Patent 5,812,672 expires which had a PCT filing in Oct 1992

**Comment by Wallacoloo** [comment]
Let's continue this mp3 discussion over on #2000 to avoid cluttering the original issue.

**Comment by Reaper10** [comment]
Please look at this Sample Track Playback Bug #2001.

**Comment by tresf** [comment]
Stop littering again.  You will be banned.

**Comment by Reaper10** [comment]
The Sample Track needs a pitch knob and pitch range box.  This way you can do a tape stop FX right form The Sample with out a plugin. You can all so just drop down the pich of the track with out a plugin to do it.

**Comment by tresf** [comment]
^--- added.

**Comment by Reaper10** [comment]
Could you add the amplify knob from the AFP to the Sample Track it'll act  as what other DAWs call the clip gain fader?

**Comment by Moth-Tolias** [comment]
bug. Quite surprised this hasn't been reported before, actually.

-put a sufficiently long sample in the sample-track (Most notable if you put a whole song in)
-hit "play"
-notice that:
--a: sample-track waveform becomes out-of-sync with currently playing audio
--b: audio stops prematurely

**Comment by tresf** [comment]
@Moth-Tolias  added to bugs section.

**Comment by Reaper10** [comment]
The Sample Track should have drag & drop support of a audio file to add a sample track with the audio file in it. This way a user can  drag & drop a audio file on a blank spot on the Song Editor to add a Sample Track with the audio file in it. This just to add another way to add a sample Track.

**Comment by Reaper10** [comment]
This is no big deal if you don't want to use this idea I just thought it would be good, it's to change the sample track icon to this,
![new icon](https://cloud.githubusercontent.com/assets/8137561/9389891/21744848-4733-11e5-8815-185c815d28ec.png)

why? it's to make the icon look nothing like the AFP icon. This way a user can't mistake one track for the other. 

Thoughts

**Comment by tresf** [comment]
> Thoughts

That is not an icon at all, it is a large waveform.  It won't scale to size.  And yes, we've tried using waveform icons and haven't settled on anything yet.

**Comment by Reaper10** [comment]
what size do you need I'm happy to resize it?

**Comment by musikBear** [comment]
@Reaper10 the wave-spectrum inside the sample-track is in fact the **actual** spectrum of the *specific* wavefile. *Not* an icon, but a representation of the **actual** spectrum

**Comment by drummyfish** [comment]
Is anyone working on "playing samples mid-song"? I've seen in #131 it was being worked on, already partly done and then closed on may 2014 until now.

**Comment by tresf** [comment]
> Is anyone working on "playing samples mid-song"? I've seen in #131 it was being worked on, already partly done and then closed on may 2014 until now.

@diizy started it via https://github.com/diizy/lmms/tree/sampletrack (about a 18 months ago) but the timing was off each time we tested this build.

Coincidentally, the timing was off the exact offset of the preview image, although he claimed at the time they were two unrelated coincidences.

In regards to it being closed, it was consolidated, not closed.  You're asking in the right place by posting your questions here. :+1:

**Comment by tresf** [comment]
Edit... this sample-track-mid-song code hasn't been touched since then, anyone is free to clone is code and continue working on it.

**Comment by Reaper10** [comment]
As brought up in #2154 the sample track needs a audio clip editor like the midi and automation editor/

**Comment by musikBear** [comment]
Could the purpose of *Sample-track* have been 'misunderstood'? When was sample-track introduced, and by who? Tobydox is my guess, but in case someone knows better, please say:)
Sampletrack has been understood as the place to have long pieces of sound-files, like a vocal, but sampletrack can be used completely different. I wonder if *that* perhaps was the actual intended usage.
Regard sampletrack as **loopSample-track*, eg Not for *long* recordings, but for **tiny loops**, and it is a very interesting feature. and one that works 100% correctly!
It is hard to explain, but very easy to see: https://youtu.be/cCTaCs_8j2M
(i apologize the reverb, but thats a camStudio problem that has appeared in my recordings)

**Comment by Umcaruje** [comment]
The purpose of sample tracks is holding __samples__, no matter now long or short, sample tracks need to accommodate to them. 

Now, in your video, you change the BPM of your song, so your project gets adjusted to the sample track and the loop is on beat. __That's not how sample tracks should work__. One should be able to accommodate the sample to fit to your project and not vice-versa. 

So, LMMS should actually try to guess the BPM of your sample, or dig it from the metadata, or allow you to set it yourself, then it should stretch that sample and make it match the BPM of your project, so if you change the tempo, the sample still stays on the beat. Sample tracks should be playable from any part of their length, no matter how short or long they are. Also, it should be possible to cut sample tracks, split and rearrange them.

Anyways, that's how ideally sample tracks should work, and I know there needs to be a lot of work done to make that happen. I just wanted to say that we can't say that an unfinished part of the program has a misunderstood purpose, just because it works in a very specific and limited usecase.

**Comment by musikBear** [comment]
@Umcaruje 
> I just wanted to say that we can't say that an unfinished part of the program has a misunderstood purpose, just because it works in a very specific and limited usecase

But thats just it. It is not a very specific and limited usecase. You can take *any* loop and use that as a fill in your own track, and any number of loops, provided that they have the same BPM. The current sampletrack is infact ACID-studio. The program that was purchased by SONY and were then made into SONYacid. Sony sells sample*packs* that has high quality recordings in the same bpm setting, and users the lego-build predominately hiphop beats, with these blocks. AFAIK audacity can change the bpm in a sample, and those could be used in LMMS -I agree that it would be marvellous, if the program could do this 'stretching', but doing it 'handmade' is not that bad. Current sampletrack is a feature, that way. It is as good as the old AcidStudio from 199x. 
..And btw, the way a sample behaves when the bpm is adjusted, is a strong indicator, that *this* is actually its **intended** usage. Dont you think so?

**Comment by musikBear** [comment]
**Rethinking Sample-track**
I here suggest a new type of track for long samples. The idea will take care of 
*Play Sample Track mid-song #(131 & 2596)*


As a wip name i have chosen **accompaniment-track**
I suggest to re-think the problem that exists with current sampletrack, eg the fact that a long recording cant be accessed from any position.
The suggestion is to threat a sound-file (wav, ogg) as a *fragmented-sample*.
To achieve this lmms would need :
* a method that can create fragmented-samples from sound-files
  * these fragments could be uniform in length, but it would make sense to implement a dB-fragmenticing as well, because sound-file-fragments can be used in several ways (sb). The creation of fragments would either be done once, and the fragments would then need to be saved in folder as a collection of wave-files, or it could take place, at every project-loading. The benefit here would be that the orr. sound-file would be used.
* load these fragments in continuous fashion in the accompaniment-track.
I suspect that it will be necessary for the fragments to be sliced at 0dB, in order to avoid clicks

The result would be a collection of sound-files, that would play as one continuous wave-file, and almost play in any position of the playhead

In mockup it could be something like:

![accomplimenttrack](https://cloud.githubusercontent.com/assets/6662066/19160923/104b0e26-8bf2-11e6-9905-99fbbda9fb37.png)

Here there are 9 fragments, and playback would be initiated at every red line, witch also is at 0dB

A possible startpoint could be with http://freecode.com/projects/freecycle
If that team would be interested in sharing, then that code may be the way ahead.
More: http://freecycle.redsteamrecords.com/
Source: http://download.savannah.gnu.org/releases/freecycle/freecycle-0.6.1.1alpha.tar.bz2

Further use of the sound-file-fragments.
The method to 'fragmentize' long sound-files into 'natural' fragments at 0dB points, could be used for a **native lmms sampler**.
Based on AFP, the plugin would distribute the fragments over the necessary number of keys, and add a real sampler functionality to lmms.
It would be kind of an AFP with a library of file references to fragments.

I also think that if only the current sample-track was given a FX-connection, it would be perfect as a loop container, so i **DEFINITIVELY** do **NOT** recommend removing current Sample-track functionality from LMMS. Current functionality allow LMMS to be used as a LoopEngine and actually gives LMMS same'ish power as SonyAcidStudio (not pitch and pace control, ofcause, but thats actually also quite buggy in SAS

**Comment by Spekular** [comment]
If the current sample track could start anywhere it would serve both of these purposes. I don't see the need to have two separate types.

Dealing with "fragments" would probably require "play from anywhere" to be inplemented anyway.

**Comment by musikBear** [comment]
But  afaik, *'play from anywhere'* is not possible, with current engine, and fragments, would eradicate the need (imo

**Comment by grejppi** [comment]
> But afaik, *'play from anywhere'* is not possible, with current engine, and fragments, would eradicate the need

In a way they could be the same, wouldn't they? Play from anywhere could be implemented as fragments split at every 1/192 of a beat. However I fear  this could possibly end with the same situation as the previous attempt was abandoned where you have no idea where in the audio file to start playback once the BPM is automated.

One possible solution would be to assign a BPM value to sounds placed on the track, and change their speed when the master BPM changes. This way there would always be a constant reference time that eliminates the problem. Maybe there would also be an option not to assign a BPM value which would keep the current behaviour (only play from the beginning) and perhaps call it something like... one-shot mode?

**Comment by BaraMGB** [comment]
In my opinion we should try to implement @dizzy s work on sampletrack. I know that automate the tempo wouldn't work. But better to have a sample track which works with a static tempo and one can start from any song position than our damn unfortunately situation with this.

**Comment by tresf** [comment]
> you have no idea where in the audio file to start playback once the BPM is automated.

This problem is a tough cookie to crack.  If we were to do 80/20 rule (focus on 80% of use-cases rather than 20% of use-cases), let's agree that the changing of tempo will need to be addressed but must be done as a separate task.

> In my opinion we should try to implement @dizzy s work on sampletrack.

He had a working example but there were performance issues and the timing was off.  I had a [theory about it all](https://github.com/LMMS/lmms/issues/131#issuecomment-44074491) but he seemed to disagree.

**Comment by musikBear** [comment]
I fully support @tresf in respect to presenting a solution for sample-track with no tempo change ability, That specific issue can be solved outside lmms (audacity), the current **LMMS**-issue is (imo) that lmms does not support vocal/ recorded-tracks in a usable fashion. I have already presented a very simple idea in 2014:
https://www.youtube.com/watch?v=v-4G_5d1ggU
Again NO BPM fitting neither. ..But it could 'work'

The 'fraction-idea' is much more advanced, but has the added advantage as being usable in a sampler-model, and the links points to an open source project, for exactly that :)
Imo the tempo-modification of samples, and fitting of BPM is not *bound* to a "accompaniment-track". If these two could be intellectually separated, my feeling is that it would be a benefit for the whole process. 
-and fgs ! do **not** dump current sample-track, it is **pure magic** with loops!

**Comment by BaraMGB** [comment]
https://youtu.be/nHq0c9-Njdc

**Comment by musikBear** [comment]
@BaraMGB You have FIXED that!
Best fix since lmms got connections to vst-dials 
Huge thanks! 💯

**Comment by BaraMGB** [comment]
There's a lot to do, yet. And tempo automation isn't possible. But it could be a start.

**Comment by tresf** [comment]
> @BaraMGB You have FIXED that!

IIRC there were [tempo sync](https://github.com/LMMS/lmms/issues/131#issuecomment-43939147) (fixed, not variable) and [performance](https://github.com/LMMS/lmms/issues/131#issuecomment-43846933) issues with the previous attempt.  The YouTube video looks like performance is fixed, how's the syncing?

This feature is very exciting indeed.

**Comment by BaraMGB** [comment]
>The YouTube video looks like performance is OK, how's the syncing?

If you look at the video: the sampletrack is a rendered version of the bb track. Both plays perfectly synced. If I cleaned up and fixed some problems I can provide a PR. 

But for automating the song tempo we need really a better solution (e.g. tempo track)

**Comment by musikBear** [comment]
@BaraMGB 
> There's a lot to do, yet. And tempo automation isn't possible. But it could be a start.

Imo it is more than a start. Ofcause tempo-synch is the holy grael, but lets say that *never* comes, even then, this what you have here is just super, because the problem with *no-play* inside a recording is by far the worst. Tempo-synch can be done in audacity, and it is honestly *not* a must-have feature in lmms, whereas *play-inside-recording* very much **is** a lmms must! Imo you **have fixed** this 🍾

**Comment by BaraMGB** [comment]
I want to invite everyone for testing the sample track in RC2. Thanks for testing.

**Comment by mrrm92** [comment]
Excuse me, I just wish to insist on BPM matching and general stertching of sample tracks, as suggested by Umcaruje.

**Comment by BenMcLean** [comment]
LMMS can't really be even considered as even a partial replacement for FL Studio until it has the ability to cut up samples and change pitch and tempo. Doing that separately in Audacity doesn't make sense because in that case you have to know exactly what you want ahead of time and type it in as exact numbers instead of experimenting. This is a creative process and FL Studio does it in one fast interface.

**Comment by BaraMGB** [comment]
@BenMcLean we all are aware of the issues you pointed out. But what can you do to help?

**Comment by tresf** [comment]
We do have a request for testing on #3947 for those willing to test.  Please jump on our chat server to help push this forward.  https://lmms.io/chat.

In regards to slicing samples, to @BaraMGB's point, we need help first and foremost.  Our mission statement isn't to be a full replacement to commercial software so these types of comments often do more harm than good.

**Comment by BenMcLean** [comment]
> we all are aware of the issues you pointed out.

Evidently not, because I was responding to the guy who said, "Tempo-synch can be done in audacity, and it is honestly not a must-have feature in lmms," to point out that it is totally a must-have feature.

> But what can you do to help?

I don't know. This is such a basic feature that the whole project is kind of a non-starter without it, no offense meant. If I was going to get into music programming, I'm not sure if I'd be adding this to LMMS or making a whole different program specifically dedicated to sampling from the ground up.

> Our mission statement isn't to be a full replacement to commercial software

Yes it totally is. From the README:

> LMMS is a free cross-platform alternative to commercial programs like FL Studio®

**Comment by tresf** [comment]
@BenMcLean please rant elsewhere.  This is your first warning.  This thread is a place to talk about adding functionality, not complain about it.  If you have problems with the way we've worded our front page, please open an issue here: https://github.com/LMMS/lmms.io/issues/new.

Our mission statement is to provide a free, cross-platform tool for making music.  In order for it to remain free, we need help, not hindrance.  Stuff like "LMMS is a non-starter" is an opinionated editorial and belongs elsewhere.

On the other hand, if you have insight into implementing this feature, this is the correct place to start.

**Comment by Spekular** [comment]
Alternative to != exact replacement. If you want sonething that's exactly
like FL Studio, that already exists. It's called FL Studio.

**Comment by tresf** [comment]
@Spekular please do not fuel the arguments, we need to move this conversation elsewhere, perhaps Discord https://lmms.io/chat, but not here.

**Comment by Spekular** [comment]
Should "FX Mixer Support" be checked now that master allows sample tracks to be sent to FX channels?
I would also propose a related enhancement, "Settings per Clip". Applying different effects, volume adjustments, and fx mixer channels to different samples in the same track would be very flexible *cough* and FL Studio does it *cough*.

**Comment by Spekular** [comment]
Just noticed "Drag samples to new TCO segments" is also implemented in master. Sidebar samples, at least, can be dragged in. You can't drop a file on lmms to add a TCO, but that seems a bit like a separate issue or sub-issue.

**Comment by BenMcLean** [comment]
I have always wanted a way to quickly chop samples and add a distinct pitch and time stretch (adjusting pitch and time stretch separately) to each piece. FL Studio gets close to that with its WaveTraveller but not close enough.

**Comment by qnebra** [comment]
This:  [Sample distinction via naming / color coding] was partially done via #5573 
It was possible to differ each sample in sampletrack via their own colors.

**Comment by Spekular** [comment]
Good point! I checked off `Colorization support #1360`, and removed the `/ color coding` part of `Sample distinction via naming / color coding` since it was redundant.

Since samples can be dragged from the sidebar to a sample track I also checked off `Easier access to built-in samples, probably through drag/drop #4221`. I added `Drag samples in from other applications` to that section since that's a request I've seen.

**Comment by Rossmaxx** [comment]
hey can you add #6390 to this list.

**Comment by luzpaz** [comment]
Can this tracking ticket be updated so we know where we're at ?

**Comment by Spekular** [comment]
@luzpaz as far as I can see, the checklist in the main issue still accurately represents the sample track's current functionality.

**Comment by messmerd** [comment]
I've reopened all issues that were consolidated into this meta issue and marked as closed without actually being implemented. ([see this comment](https://github.com/LMMS/lmms/pull/7851#issuecomment-3621573077))
