### ISSUE TITLE
New default shortcuts (table)

### ISSUE THREAD

**Issue by Sti2nd** [LMMS/lmms#1488]
#### Phase 4; Revision 1 in progress

**Goals:**
1. Same key for same action across different Editors, and parts of the program.
2. Easy to remember and fast/easy to press.
3. Future compatible! Should allow new futures added into LMMS. For example https://github.com/LMMS/lmms/issues/1421 This can be hard to predict, therefore low importance.

Tables based on the existing http://lmms.io/wiki/index.php?title=1.0:Key_Mappings
SE = Song Editor, PR = Piano Roll, AE = Automation Editor
### Piano Roll

| Existing shortcut key | Action | Attention because | New shortcut key |
| --- | --- | --- | --- |
| Ctrl + C | Copy selected notes |  | Same |
| Ctrl + V | Paste copied notes |  | Same |
| Ctrl + X | Cut selected notes |  | Same |
| Ctrl + A | Select all notes |  | Same |
| Ctrl + Shift + A | Deselect all notes |  | Implemented |
| Esc | Deselect all notes |  | Implemented |
|  | Copy selected notes and paste them at the end of the last note in the Piano Roll | Awesome | Ctrl + D |
|  | Deselect everything | Useful | Ctrl + Shift + A |
|  | Sustain pedal https://github.com/LMMS/lmms/pull/1632 |  | Shift |
| Shift-D | Select draw tool |  | Same |
| Shift-E | Select erase tool |  | Same |
| Shift-S | Select selector tool |  | Same |
| Shift-T | Select detuning tool |  | Same |
|  | Select razor tool / Split selected notes. Also in PR https://github.com/LMMS/lmms/issues/746 |  | Shift + R (reserved) |
|  | Select glue tool / Merge selected notes. Also in PR https://github.com/LMMS/lmms/issues/746 |  | Shift + G (reserved) |
| Ctrl | Temporarily use the select tool. Temporarily select mode. | Inconsistent with SE | Same |
| Shift + click when in select mode | Add to selection and deselect selected | Inconsistent with SE | Same |
| Ctrl + Shift + click | Temporarily add to selection | Inconsistent with SE | Same |
| Delete | Delete selected notes |  | Same |
| Right click | Delete note | Inconsistent with SE's delete segment | Middle mouse & Shift + Right click |
|  | Show context menu for note |  | Right click (reserved) |
| Left click | Place note |  | Same |
| Left click on empty area + Shift | Fast resize |  | Same |
| Left click on empty area + Shift + Alt | Fast resize without quantization |  | Same |
| Alt | Temporarily disable quantization | Inconsistent with SE's fine adjust and fine move | Same |
|  | Duplicate and move selection with arrow keys https://github.com/LMMS/lmms/issues/625 | Useful | Ctrl (+ something) + Arrow keys |
| Shift + Drag (selection) | Duplicate selection and move those notes | Inconsistent with SE's clone selection | Same |
| Shift + Drag on right edge of note in selection | Reduce size and move selected notes correspondingly |  | Same |
| Shift + Ctrl + Drag on right edge of note in selection | Reduce size and move selected notes and all notes to the right of selection. |  | Same |
| Arrow Keys | Scroll | Inconsistent with SE | Same |
| Ctrl + Up | Move selected notes up one octave |  | Same |
| Ctrl + Down | Move selected notes down one octave |  | Same |
| Ctrl + Left | Move selected notes one bar left |  | Same |
| Ctrl + Right | Move selected notes one bar right |  | Same |
| Shift + Left | Move selected notes one quantization value left |  | Same |
| Shift + Right | Move selected notes one quantization value right |  | Same |
| Shift + Up | Move selected notes one semitone up |  | Same |
| Shift + Down | Move selected notes one semitone down |  | Same |
| Num Pad | Change note length |  | Same |
|  | Insert bar immediately after play head position | Consistency, see SE | Shift + Insert (reserved) |
|  | Delete bar immediately after play head position | Consistency, see SE | Shift + Delete (reserved) |
| Ctrl + Mouse scroll wheel OR touch pad gesture | Zoom |  | Same |
|  | Opens next pattern (in Song Editor) in Piano Roll |  | Alt + Right Arrow Key |
|  | Opens previous pattern (in Song Editor) in Piano Roll |  | Alt + Left Arrow Key |
|  | Don't adjust overlapping notes' volume | https://github.com/LMMS/lmms/pull/1804 | Alt + Super? |
### Song Editor

| Existing shortcut key | Action | Attention because | New shortcut key |
| --- | --- | --- | --- |
|  | Cut selected values |  | Ctrl + X (reserved) |
|  | Copy selected values |  | Ctrl + C (reserved) |
|  | Paste previously selected values |  | Ctrl + V (reserved) |
|  | Select all values |  | Ctrl + A (reserved) |
|  | Deselect all values |  | Ctrl + Shift + A |
| Left click on track | Place segment/TCO |  | Same |
| Right click on segment | Show context menu for segment editing |  | Same |
| Middle click on segment OR Shift + Right click | Delete segment | Inconsistent with PR's delete | Same |
|  | Delete selection | Consistency, useful | Delete (reserved) |
| Ctrl + middle click on segment OR Ctrl + right click | Mute segment |  | Same |
| Ctrl pressed before drag on segment | Copy segment | Inconsistent with PR's clone/duplicate | Shift |
| Ctrl + drag on 'grip' section of track | Clone track. | Inconsistent with PR's clone | Shift |
|  | Clone track without the effects chain. | Useful |  |
| Left mouse button drag on segment | Move segment |  | Same |
| Ctrl pressed after drag on segment | Fine move / high precision move | Inconsistent with PR's disable quantization | Alt |
| Left mouse button drag on end of B&B segment | Resize |  | Same |
|  | Resize pattern with notes | https://github.com/LMMS/lmms/issues/1648 | Left mouse button drag on end of instrument pattern |
| Ctrl pressed when resize segment | Fine resize |  | Alt |
| Shift + drag vertically on empty part of track | Resize track height |  | Same |
| Shift + Insert | Insert bar immediately after play head position |  | Same |
| Shift + Delete | Delete bar immediately after play head position |  | Same |
|  | Insert X bars immediately after play head position |  |  |
|  | Delete X bars immediately after play head position |  |  |
| Left and Right arrows | BROKEN? Move play point one bar back or forward | Inconsistent with Piano Roll scroll | Remove existing code to achieve scrolling functionality!?! |
| Up and Down arrow keys | Scroll |  | Same |
|  | Select draw tool | Useful, consistency | Shift + D (reserved) |
|  | Select erase tool | Non existing? | Shift + E (reserved) |
|  | Select selector tool | Useful, consistency | Shift + S (reserved) |
|  | Temporarily use the select tool | Useful, consistency, see PR | Ctrl (reserved) |
|  | Select razor tool / Split selected patterns = fast razor. https://github.com/LMMS/lmms/issues/746 |  | Shift + R (reserved) |
|  | Select glue tool / Merge selected patterns. https://github.com/LMMS/lmms/issues/746 |  | Shift + G (reserved) |
| Ctrl + Mouse scroll wheel OR touch pad gesture | Zoom |  | Same |
|  | Move focus to next pattern |  | Alt + Right Arrow Key |
|  | Move focus to previous pattern |  | Alt + Left Arrow Key |
### Automation Editor

| Existing shortcut key | Action | Attention because | New shortcut key |
| --- | --- | --- | --- |
| Shift + Left Click | Draw a straight line between this point and the previously clicked point | Redundant ? |  |
| Left and right arrows | Move the play head position left and right | Inconsistent with PR | Remove existing code to achieve scrolling functionality!?! |
|  | Cut selected values |  | Ctrl + X (reserved) |
|  | Copy selected values |  | Ctrl + C (reserved) |
|  | Paste previously selected values |  | Ctrl + V (reserved) |
|  | Select all values |  | Ctrl + A (reserved) |
|  | Select draw tool |  | Shift + D (reserved) |
|  | Select erase tool |  | Shift + E (reserved) |
|  | Select selector tool |  | Shift + S (reserved) |
|  | Delete selected values |  | Delete |
|  | Temporarily disable quantization |  | Alt |
| Ctrl + Mouse scroll wheel OR touch pad gesture | Zoom |  | Same |
### (Editors with) Time line and playback controls

| Existing shortcut key | Action | Attention because | New shortcut key |
| --- | --- | --- | --- |
| Left-click on timeline | Move playback position to that time |  | Same |
| Shift + right click OR Middle click on timeline | Move loop start point to that time | Illogical / hard to remember | Shift + Left click |
| Shift + Ctrl + right click OR Ctrl middle click on timeline | Move loop start point to that time exactly | Illogical / hard to remember | Shift + Alt + Left click |
| Right click on timeline | Move loop end point to that time |  | Shift + Right click |
| Ctrl + right click on timeline | Move loop end point to that time exactly |  | Shift + Alt + Right click |
|  | Move both loop markers |  | Shift + left click + right click (is this easy enough on laptop?) |
| Space bar | Start or stop playback |  | Same |
|  | Play and pause playback | Useful | Shift + Spacebar |
| Home | Move play head to beginning |  | Same |
|  | Move playhead to end of song | Useful | End (reserved) |
|  | Move playhead X bars forward |  |  |
|  | Move playhead X bars backward |  |  |
### Other

| Component | Existing shortcut key | Action | Attention because | New shortcut key |
| --- | --- | --- | --- | --- |
| Pop up windows | Esc |  | Cancel | Same |
| Window menu | Ctrl + F4 | Close window |  | Same |
| File browser | Alt + F5 | Refresh file list |  | Same |
| FX mixer | Left Arrow and  Right Arrow | Change selected FX channel left and right |  | Same |
| FX mixer | Alt + left/right arrow key | Move selected channel left/right |  | Same |
| FX mixer |  | Add new channel | Useful | Shift + Insert (implemented https://github.com/LMMS/lmms/pull/1980) |
| Fx mixer |  | Add X number of new channels | Useful | Insert + number (reserved) |
| Main Window | Arrow keys | Scroll |  | Same |
|  | Give focus to search bar | https://github.com/LMMS/lmms/issues/2013 | Ctrl + F |  |
### Instrument Plugins

| Existing shortcut key | Action | New shortcut key |
| --- | --- | --- |
| Shift + drag on control | Copies the value of the clicked control and paste the value on the released knob. | Same |
| Ctrl + drag on control | Connect control. | Same |
| Middle mouse scroll on knob OR Shift + drag | Fine adjust knob values l Alt + drag (middle mouse scroll stays) |  |
### Project Notes

| Existing shortcut key | Action | New shortcut key |
| --- | --- | --- |
| Ctrl-X | Cut selected text | Same |
| Ctrl-C | Copy selected text | Same |
| Ctrl-V | Paste selected text | Same |
| Ctrl-B | Toggle bold text on/off | Same |
| Ctrl-I | Toggle italic text on/off | Same |
| Ctrl-L | Left justify text | Same |
| Ctrl-E | Centre text | Same |
| Ctrl-R | Right justify text | Same |
| Ctrl-J | Justify text to both margins | Same |
### Main Window (i.e. works anywhere)

| Existing shortcut key | Action | New shortcut key |
| --- | --- | --- |
| F6 | Show Beat + Bassline Editor | Same |
| F7 | Show Piano Roll Editor | Same |
| F8 | Show Song Editor | Same |
| F9 | Show Automation Editor | Same |
| F10 | Show Project Notes | Same |
| Ctrl-N | Create a new project | Same |
| Ctrl-O | Open an existing project | Same |
| Ctrl-S | Save current project | Same |
| Ctrl + Alt + S | Save as new version | Same |
| Ctrl-Shift-S | Save current project under a new name | Same |
| Ctrl-E | Export current project to WAV or OGG | Same |
| Ctrl-Q | Quit LMMS | Same |
| Ctrl-Z | Undo _Partially_ | Same |
| Ctrl-Y | Redo _Partially_ | Same |
| Page up | Scrolls "one page" up | Same |
| Page down | Scrolls "one page" down | Same |
| Mouse wheel up or down OR touch pad scroll | Scroll up or down = vertical | Same |
| Shift + mouse wheel OR horizontal mouse wheel OR touch pad scroll | Scroll left or right = horizontal | Same |
| Ctrl + Tab | Toggles between the different open windows in LMMS. | Same |

**Needs to be coded** Very unfinished WIP
- [ ] Copy Piano Roll delete behavior https://github.com/LMMS/lmms/issues/1500
- [ ] Add erase button (mode) to Song Editor and then address this problem, maybe fixed with the above. https://github.com/LMMS/lmms/issues/980
- [ ] Select tool in Automation Editor
- [ ] Autoscroll when using select tool https://github.com/LMMS/lmms/issues/1523
- [ ] All segments/patterns should be resized when they are all selected in Song Editor
- [ ] Clone track without the effects chain, a.k.a just the instrument and it's notes. Should work when dragging in from the sidebar primarily.

**Related to:**
https://github.com/LMMS/lmms/issues/1338 https://github.com/LMMS/lmms/issues/1144 https://github.com/LMMS/lmms/issues/1122 https://github.com/LMMS/lmms/issues/535 https://github.com/LMMS/lmms/issues/1429 https://github.com/LMMS/lmms/issues/1421 https://github.com/LMMS/lmms/pull/728 https://github.com/LMMS/lmms/issues/822 https://github.com/LMMS/lmms/issues/746 https://github.com/LMMS/lmms/issues/615 https://github.com/LMMS/lmms/pull/1553 https://github.com/LMMS/lmms/issues/1643 https://github.com/LMMS/lmms/issues/625 https://github.com/LMMS/lmms/issues/621

Could be debatable if one should change the default ones before https://github.com/LMMS/lmms/issues/1475

**Comment by Sti2nd** [comment]
Ok, so this is what I propose @tresf @softrabbit @diizy @musikBear @Umcaruje @SecondFlight @Spekular 

Now you should look in the New Shortcut Key column. Where it stands (reserved) the function is not yet coded. Where it doesn't stand Same or (reserved) it is a new shortcut.

Here is a document overview over which keys the inconsistent ones have turned into, also explains a little. https://docs.google.com/document/d/1rcSMpBdKFOSTHV5xi8y2gXUxz7PBzpi4gC5TQs_9eWQ/edit?usp=sharing

**Comment by Spekular** [comment]
Looks good to me. Might be easier if the old keys were listed for
comparison and the explanation were moved to a separate column.

**Comment by Sti2nd** [comment]
@Spekular I understand you have been looking at the google document, the old list is in the top table ^ and the new shortcuts too, but not the reason for the new keys.

**Comment by Spekular** [comment]
Oh! I was looking at this from my mail, so the first post wasn't updated.
Oops.

**Comment by Spekular** [comment]
I definitely like alt for precision, and I'd love if you could press alt
befire dragging to precision move/scale patterns (pressing afterwards feels
odd). Also perhaps just space or shift space for play? Ctrl seems to be
mostly for selection whereas shift seems to be the main modifier key.

**Comment by Sti2nd** [comment]
> shift space for play

and pause. Good call, it will work either way, but you are right in that Shift might be more logical, updating the table now.

**Comment by tresf** [comment]
> I'd love if you could press [modifier] **before** dragging to precision move/scale patterns (pressing afterwards feels odd).

:+1: :+1:

**Comment by Sti2nd** [comment]
> I'd love if you could press [modifier] before dragging to precision move/scale patterns (pressing afterwards feels odd).

The proposal will allow this indeed, but it needs to be coded first :)

**Comment by Spekular** [comment]
@sti2nd You've probably already seen these in 1562, but issues 1643, 1500, 1488, 615, 625, 621, 1475, 1421,and 741 are all related to shortcuts. (Attempting to not link everything together like I did over there by leaving out the # , sorry for the inconvenience)

**Comment by badosu** [comment]
Just found that a new shortcut was not documented, see #605. Using `<Alt-left/right>` when selecting a mixer channel moves it.

@tresf @Sti2nd Can we find a nice place on https://lmms.io/documentation/Manual to put this information?

**Comment by tresf** [comment]
@Sti2nd or Umcaruje are prob the best candidates to add content although IIRC we allow registrations again so others can help.

**Comment by Sti2nd** [comment]
@badosu Already updated this table, and yes, when the table is officially going to be implemented I am going write a new table on the wiki below the old one and when a new LMMS with the keys is officially out we can perhaps remove the old table. That is the plan. When I asked about devs and documentation, however, I were wondering how devs would like to document their work. Do you want to write directly to the wiki? Do you want to share a Google doc, gist or whatever? Or the worst option and as it seems like it is working now, are you going to write comments in the code and let other people try to understand and document...

> IIRC we allow registrations again

Not that I can see, and that is a very big problem. Uros has offered to make an account for everyone who want's, but I can understand people being more hesitant to ask a person rather than a system. We have had 0 new users on the wiki after Christmas and we even asked on Facebook for help.

**Comment by tresf** [comment]
> Uros has offered to make an account for everyone who want's

That's better than nothing.  :)

**Comment by Umcaruje** [comment]
I can enable the account creation, but that can produce a lot of spam. IIRC spam is the reason this was disabled in the first place. I think this is better off being discussed on https://github.com/LMMS/lmms.io/issues/99 though, for consistency :)

**Comment by tresf** [comment]
> I can enable the account creation, but that can produce a lot of spam. IIRC spam is the reason this was disabled in the first place. I think this is better off being discussed on LMMS/lmms.io#99 though, for consistency :)

Agreed.  We don't have dozens of people knocking on the wiki door.  We'll enable this if demand warrants it.  In my experience only a select few actually enjoy the documentation process, so our existing model works well for now. :+1:

**Comment by badosu** [comment]
I need to document something here: https://github.com/LMMS/lmms/pull/1716, how can I help?

**Comment by tresf** [comment]
This thread is probably better than the wiki for now.   It is hard to maintain a current and future table for these things, so I will ask @Sti2nd to provide a recommendation.

**Comment by Sti2nd** [comment]
> I need to document something here

Already documented that, but do you have access to the table? In that case you could in the future add it in the "existing shortcut key" column, and then explain the action in the "action" column. I should probably be notified cause if it is conflicts with the future table I have to fix it :)

**Comment by Sti2nd** [comment]
@Lukas-W @tresf Would this behavior be possible to code: Holding Shift + S down in an Editor and then dragging selects patterns/notes. If you then release the keys the selection is kept and you go back to the last mode (draw mode). If you didn't drag, only hit Shift + S, you enter select mode.

Reason is because LMMS currently uses Ctrl for fast select in Piano Roll, and you can't use Ctrl to clone/duplicate notes when fast select is mapped to it. As Tres pointed out duplication with Ctrl is standard in most file browser, so I have to change the fast select key combo. Also I think it is unfortunate to occupy Ctrl for fast select, there are only three different modifier keys available: Alt, Ctrl, Shift, so occupying one isn't especially smart.

The other solution I had in mind was to use Shift for fast select, it might be doable, but I still thinks it is stupid to occupy 1/3 of the available modifiers for that. Also with Shift as fast select you wouldn't be able to use it when hovering over notes.

**Comment by tresf** [comment]
> you can't use Ctrl to clone/duplicate notes when fast select is mapped to it.

Unless we make one behavior when a note/notes is clicked and the other when an empty area is clicked.

**Comment by tresf** [comment]
> but do you have access to the table

No one except for you and GitHub admins can edit your posts.

**Comment by Sti2nd** [comment]
> Unless we make one behavior when a note/notes is clicked and the other when an empty area is clicked.

Thought it would be a little annoying, don't know... Do you think holding down Shift + T is fairly easy, or do you think that is going to be hard to do fast?

> No one except for you and LMMS/lmms admins can edit your posts.

Oh, ok. I kinda thought he was some kind of admin.

**Comment by tresf** [comment]
> Oh, ok. I kinda thought he was some kind of admin.

Not yet. :)

> Thought it would be a little annoying, don't know... 

Again, compare this to existing GUIs.  If you hold a Ctrl modifier key when selecting files from an empty region, you don't expect it to have the same effect as when you hold Ctrl when dragging files, do you?

**Comment by Sti2nd** [comment]
No, I don't expect that. It could work in the Piano Roll where the notes aren't covering all the empty areas, but in the Song Editor though. How can I select the highlighted patterns?
![image](https://cloud.githubusercontent.com/assets/6373430/6092423/936ebf34-aede-11e4-8351-1261882291f3.png)

**Comment by tresf** [comment]
Hmm.. You have a good point.... Perhaps varies based on the selection size?

**Comment by Sti2nd** [comment]
Ehhh, could you elaborate? Selection size?

**Comment by Sti2nd** [comment]
So I can't work out how we can combine Ctrl for duplication and fast select in Song Editor. I looked at GIMP with its tools and it uses 'r' (for rectangle select), but it isn't fast select.The 'r' key in GIMP chooses the tool. So I propose to make use of the different tools/modes in a similar manner, Shift + S will let you go into selection mode where you can select, add and substract from selection. (Just 's' cannot be used because of playing notes with the computer keyboard in the Piano Roll)

Later/at the same time one can perhaps implement some kind of fast select by detecting Ctrl + S + Drag and then instead of choosing selection tool go back to the previous tool.

More reasons for using Shift + S:
- Frees up an important modifier key!
  - Which in turn is more sustainable when thinking about the future
- Is logical and enforces the idea of tools and their shortcuts (Shift + Name on tool)
Downsides
- Two shortcuts is of course harder to press than one
- This will most likely make it harder or impossible to do fast add/subtract from selection.

**Comment by tresf** [comment]
@Sti2nd please update `CTRL + SHIFT + A` per #1693.

**Comment by Wallacoloo** [comment]
That should have been a reference to #1963 :P

**Comment by Sti2nd** [comment]
Yup, Tres, added. Reason I haven't made progress on this is partly BoL v2, partly life, and partly that I didn't manage to build LMMS on my Ubuntu when I tried this Easter. Not sure I'll have so much more time now since exams are coming up, but I will definetely try again to build somewhere after 22nd of May. 
If you want to help.
I think the problem I had was with Qt. That was what the terminal was complaining about at least, after I actually managed to install all dependencies. Also I tried to build on 64 bit Ubuntu so had to install alternative library for some lib, since it weren't compatible... Back to Qt. Qt5 can be downloaded as an executable and so I first tried with that one by setting the flag -DWANT_QT5=ON. That didn't work, I think because LMMS didn't find the correct path, but setting the additional flag didn't help https://github.com/LMMS/lmms/blob/master/INSTALL.Qt5
So I tried to install Qt4, but couldn't find an executable and didn't mange to build that correctly either...
I will be back, BoL v2 is soon finished. Keep up the good work folks!

**Comment by tresf** [comment]
@Sti2nd, perhaps we track the QT5 stuff in a separate conversation?

**Comment by Reaper10** [comment]
The delete key could be used for the general keyboard shortcut delete function.

**Comment by Sawuare** [comment]
Let's get rid of `Ctrl + Shift  + A` and only use `Esc` for deselecting.
Much easier, faster and memorizable. 😉 
This will solve https://github.com/LMMS/lmms/issues/2898#issuecomment-230683540.

**Comment by tresf** [comment]
@Sawuare can we have both?

**Comment by tresf** [comment]
> @tresf We can, but why?

Because UX doesn't have to be a one-way street.  Did you know that Firefox allows `/`, 'F3' and `Ctrl + F` to search a page because they are so commonly used in other programs?

**Comment by jayknowstheway** [comment]
Is there any work done to make custom shortcuts an option? Default shortcuts are totally arbitrary and should be possible to change. Not being able to use LMMS without a mouse is actually my biggest reason for not using it, but even if I were able to and had shortcuts I couldn't change.. that would be tough.

**Comment by musikBear** [comment]
@jayknowstheway Yes 1475. not sceduled

**Comment by JackyYuenDacai** [comment]
I think the drag on control really have a strict demand on having a mouse connected to the machine. Seems like currently it is almost impossible to use it only with keyboard.

**Comment by JackyYuenDacai** [comment]
Okay... I missed the one upon me

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
