### ISSUE TITLE
Better Color Handling

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#1665]
This is a placeholder to consolidate colored tracks/mixer channels/etc related issues and requests. If a new related bug is reported on the tracker, close it out and mark it as a duplicate of this bug, #1665.
## 
###### Enhancements:
- [ ] FX-mixer strip color indicating its type #1214
- [ ] Improving Colored Tracks #1176
- [ ] Enhancement: Get option to custom color instruments tracks like beat and bass tracks #1160
- [ ] Enhancement: Colors as addition to comment-tracks #560
- [ ] Color palette #2332 
- [ ] Revert to default colors/disable colors/limit colors ( no issue open yet, this is for @diizy )
###### Bugs:
- [ ] [Bug] stable-1.1 Tracks should explicitly remember last colour used. #1006

**Comment by tresf** [comment]
Off-topic... Those are some elite checkboxes!

**Comment by Spekular** [comment]
@tresf I wasn't sure how you did some of your formatting (the thin "code
block" colored line), so I read the github markup guide for the thousandth
time. They're pretty useful actually.

**Comment by tresf** [comment]
As part of a pruning effort, this `enhancement` request is archived into a dedicated "Better Workflow" checklist here #4877.
