### ISSUE TITLE
Cusis Theme Support

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#1839]
We have a hypothetical theme titled "**Cusis**" that has made a lot of commotion in the forums, mailing list, issue tracker and deviant art.

![screen shot 2015-03-08 at 2 02 22 pm](https://cloud.githubusercontent.com/assets/6345473/6546887/cdba6354-c59b-11e4-8f7c-8998ea9c85dc.png)

**History:**
 * **2009:**  Cusis releases [theme mockup design](http://cusis.deviantart.com/art/CUSIS-User-Interface-LMMS-136994117)
 * **2009:** @pgiblock starts support for Cusis theme: [old-master/src/gui/cusis_style.cp](https://github.com/LMMS/lmms/blob/old-master/src/gui/cusis_style.cpp). (backup copy [here](https://gist.github.com/tresf/c29558869a3e40abf631#file-cusis_style-cpp))
 * **2015:** Cusis re-engages with development team on [`forum/#1693`](https://lmms.io/forum/viewtopic.php?f=4&t=1693)

> @pgiblock wrote:  "I really like [this] work and I will break my back to make sure your theme and the Cusis theme make it into LMMS"

--- 

Obstacles/Milestones:
 * [ ] Beat/Bassline Preview support #1263 
 * [ ] Song Editor Graphics #150
 * [ ] Title Bar Theming Support #123

Related Bug Reports:
 * Modern/Sleek Theme for LMMS #880
 * Using QT Resource Engine #1742
 * Font size issues #541
 * LMMS Futuremap #908
 * Shaded Piano Octaves #669

---

If you think of something, post it and we'll add it to the list. :+1:

**Comment by RebeccaDeField** [comment]
I've heard of this beautiful theme before and look forward to seeing it move forward. Has the graphic artists released the source files?

**Comment by tresf** [comment]
> Has the graphic artists released the source files?

@RebeccaDeField from what I'm observing, the artist is still in the early design stages, so no, not yet.

Here's a copy of the [latest post from the forum topic](https://lmms.io/forum/viewtopic.php?f=4&t=1693&start=10#p7667):

> Here is an image of the template file i'm working on. I couldn't find / sort all of the images, as i couldn't locate them in LMMS.<br>

> The file will work like this:<br>

> Next to each default / master image there will be a duplicate image or design with a slice fitting the exact proportions of the original. All you have to do it design within that space, and then export slices. (all slices will be setup with correct file name for exporting in one go, or individually.)<br>

> I also plan to edit the css file to make it correspond to the section number on this file, so that when needing to change a background or gradient within a certain, it is a lot easier to identify and or find.<br>

> This file should be compatible for Photoshop and Fireworks.<br>
> ![image](https://cloud.githubusercontent.com/assets/6345473/6554940/4ba98b14-c637-11e4-947f-78e360a8571e.png)

**Comment by RebeccaDeField** [comment]
What a clever way of orginizing the slices. I am exporting my slices directly into the program, but this will definitly make it easier and more acessable for designers to create themes. If Cusis is interested, they can always download any of the icons, splash screens and demo graphics that I have created and modify them as they see fit.

**Comment by tresf** [comment]
Agreed. I think collaboration is key and I think the struggles we hit in code in one theme are likely to benefit both. :+1:

**Comment by badosu** [comment]
I was having a radical thought after seeing the above prototype: how it would be easier for designers to collaborate on lmms if we could support sprites. The designer would just have to bother with positioning and resizing the artwork precisely, instead of memorizing and creating a lot of files.

Of course, this would be impractical on the code-side, but perhaps we could write a script to slice sprites and automate the process of artwork creationg. This could even eliminate the need of specifying an artwork folder at all...

**Comment by tresf** [comment]
Agreed, sprites have their benefits....  Are we sure CSS can't do the sprite stuff for us?

**Comment by tresf** [comment]
Or we use a 3rd party tool to slice and dice, so we don't clutter our code... :)

**Comment by badosu** [comment]
@tresf I find it unlikely, but not impossible. There could be a way to not use 3rd party code outside of QT and LMMS main process but I would have to research.

Unfortunately I am focused on studying DSP to support LV2 and modernize our plugin suite/management on LMMS so I won't be doing this for now.

**Comment by tresf** [comment]
Fixed. :)

> Fortunately I am focused on studying DSP to support LV2 and modernize our plugin suite/management on LMMS

**Comment by badosu** [comment]
@tresf Well, unfortunately because this is totally alien for me, so it will take a while :-).

**Comment by deragon** [comment]
Just a reminder that the font size used in the current theme (the one released) is just too small, extremely hard to read on a 15" screen laptop with 1080 resolution.  This should be a priority, even if it means to hack the current theme instead of waiting for Cusis.

**Comment by tresf** [comment]
>

**Comment by tresf** [comment]
> This should be a priority, even if it means to hack the current theme instead of waiting for Cusis.

Then make it one.  We are all volunteers here that use the software too.  We know how badly these items need addressing but we lack the proper help to get them all done in a reasonable amount of time. :)

**Comment by deragon** [comment]
No time.  I have my own open source project to take care of:  http://autopoweroff.sourceforge.net

And I receive valuable input from users and never I have asked them to contribute.  The users are entitled to their opinion and can shed light on priorities.  In this case, I am pointing out that the font size is an issue for those who have sight problems (i.e. 40+ years old).  Ideally, if it is possible to increase the size in the current theme relatively easily, it should be done instead of waiting after Cusis that might take months to realize.  It is a suggestion, nothing else.

**Comment by tresf** [comment]
> No time. I have my own open source project to take care of

So do the rest of us. :+1: 

> And I receive valuable input from users and never I have asked them to contribute. 

Perhaps, but your above input is not valuable.  But of course as a coder, you already know that.  #541 brought the font size to a bug report and we've taken the time to organize and prioritize theme support, I'm not sure what value your statement "this should be a priority" adds.  It's bossy, not informative.

Furthermore, this project has a team that was mostly uninvolved code-wise one year ago.  I'm not sure if your personal project is the same way, but our bugs and our codebase are ONLY improved by our community.   The original author of LMMS is no longer our most active code contributor, so we rely solely on the help from others.

So, when you walk into a mosque and tell the community members someone should fix the crack in the wall, don't be surprised when they ask if you know how to fix walls. :+1:

**Comment by Umcaruje** [comment]
I think the issue @deragon mentions also has a connection to #455 which should be fixed when LMMS gets upgraded to use Qt 5.

**Comment by RebeccaDeField** [comment]
I think both @deragon and @tresf have a point. If I am understanding corectly, you are trying to say that although the font size is an issue in the Cusis theme, that it also needs to be an issue on the current theme. You also are trying to provide some valuable input, by letting us know that in your opinion it is very important and why.

@tresf Wants to keep the integrity of the Open Source concept, which is also important. He is also making sure that everyone understands this is not like a company where you can asign tasks unless you are doing it yourself. People work on a vulenteer basis.

My question is, has this issue already been added as an important issue on the main theme? If so, what is the first steps to making that a reality so that if someone does have time, they can do that. Should we choose a new font size, pherhaps? Or has that already been chosen? Or are we still unsure how to change the font size to begin with?

In the theme that I am creating, I am sure I will need to change the font as well so it seems this is a consistant issue.

Thank you in advance for the valuable time you spend on answering my questions.

**Comment by tresf** [comment]
> Or are we still unsure how to change the font size to begin with?

Yes that or perhaps @Umcaruje's point (which speaks about a possible technical limitation that can be addressed with switching the project to QT5).

The major problem we have with this stuff in general is that theming simply wasn't included into the design of many of our elements, font-size included.

The tremendous benefit our project has is that our build tutorial is so efficient, someone can have Ubuntu installed in a VM and have the software compiled in just a few hours.  Most of this time is waiting for Ubuntu to download the dependencies, so this is really a sit-back-and-relax type task.  So much so that many of us [actually run build environments on multiple OSs](https://cloud.githubusercontent.com/assets/6345473/6737127/0e108dfa-ce40-11e4-8841-c120a5fd09e3.png) (this really helps us troubleshoot platform-dependent issues).

The codebase is quite a bit of work to get wrapped around, but [finding a pixmap can be quite trivial thanks to the wonderful GitHub](https://github.com/LMMS/lmms/search?utf8=%E2%9C%93&q=cpuload_leds).  But most of the developers here actually manage multiple projects.  Some manage multiple LMMS projects (such as our social media pages, forums, events, our website, our sample library).

But all this said, we still have people like Dave that say "give me work!", so with a little bit of research, the cosmetic and the coding can come together, we just need more help. :balloon: 

-Tres

**Comment by diizy** [comment]
Well when it comes to font sizes, there is no one "right size", because there is no one standard DPI that all monitors use.  A font size that is "too small" for some may be uncomfortably clunky and large for others.

So considering that we're not flooded with requests to increase the font size in the default theme, I think it's safe to leave it as is for now.

That said, nothing is stopping anyone from creating a "large font theme" for LMMS. Most of the font sizes should already be configurable in CSS, if there are places where it can't be changed (settings window was one IIRC) then those need to be addressed in code. Otherwise it's up to theme makers.

**Comment by Spekular** [comment]
Anecdote; the default font size is perfectly fine for me on my 1920X1080
desktop screen and my 1366X768 laptop screen. I think font size is one area
where "just let the user decide" is the appropriate response though, so
perhaps it ought to be in the settings.

**Comment by musikBear** [comment]
Here is an image comment on readability - I am well aware that the issue is undergoing work, but my question here is simply:
Couldent the mouseover tool-tip be used to echo the block name? -better fonts are Still needed, but the readability would be significant better with mouseover ?
![readblocknames](https://cloud.githubusercontent.com/assets/6662066/9360115/a737a9f6-4694-11e5-8739-e4f28a6dac9d.jpg)

Pop quiz -What is the name of the blocks?

**Comment by tresf** [comment]
@musikBear please provide a readability enhancement report.  This should be relatively easy for a UX programmer to tackle.

**Comment by michaelgregorius** [comment]
What do you think about giving the text a semitransparent background rectangle?

![1839 - readability](https://cloud.githubusercontent.com/assets/9293269/9369340/a37af730-46c8-11e5-90b9-691512753547.png)

I have also switched the text color for muted elements from almost black to 50% gray.

Judging from the code it seems that muted elements should also have an icon:
```
if( m_pat->isMuted() )
{
	p.drawPixmap( 3, p.fontMetrics().height() + 1, embed::getIconPixmap( "muted", 16, 16 ) );
}
```
The icon looks as follows:
![muted](https://cloud.githubusercontent.com/assets/9293269/9369447/6d1f9c76-46c9-11e5-8278-817ef5f7656e.png)

Was this turned off intentionally? In case it was not I guess this is something for a new issue?

**Comment by Umcaruje** [comment]
A bit off-topic but:

@musikBear could you please crop your screenshots? Some of your screenshots have abnormal amounts of whitespace around them, which makes viewing them on mobile a nightmare.

**Comment by mamarilmanson** [comment]
Have you invited him here in github? :)

**Comment by musikBear** [comment]
@michaelgregorius 
> What do you think about giving the text a semitransparent background rectangle?
That is better, yes -but mouseover would show the name, even if the block was to short for a ..namespace :p 

(and btw the sentence *Use mousewheel to set the volume of a step* is confusing. If i, as a new user, saw that in this context, i would misunderstand the word 'step' as a bar in song-editor, and expect to be able to set the volume of *this* **block** )

@Umcaruje done -sorry, i used the wrong one in upload

**Comment by Umcaruje** [comment]
About the `Many widgets not currently themable` point: Can someone make a list of what else is not themeable? During the efforts of making the new theme, we made a lot of previously hard-coded widgets themeable, so I'm curious at what's left hard-coded.

**Comment by IvanMaldonado** [comment]
@Umcaruje Say no more, give me some time and I tell you.
