### ISSUE TITLE
Better Playhead Auto-Scroll

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#2291]
![image](https://cloud.githubusercontent.com/assets/6345473/9442530/643c7cd0-4a4a-11e5-9a68-6fe56f96f56c.png)

**Bugs**
 * [ ] Auto-Scroll ignored in record mode (#656)
 * [ ] Auto-Scroll ignored when stop is pressed (#1735)
 * [ ] Auto-Scroll off should never change the viewport (#1735)

**Enhancements**
 * [ ] Custom behavior of `<<` toggle button between stop and pause (#2284)

**Comment by midi-pascal** [comment]
Fixed Song editor scroll back bug with PR #2423

**Comment by Spekular** [comment]
An additional enhancement: Remember auto-scroll setting when LMMS is closed/reopened. Auto scroll bothers me every time I forget to disable it on startup (read: often) and I wish it would just remember it's previous state instead.

**Comment by luzpaz** [comment]
Looks like all issues mentioned here are addressed. Can this be closed ?

@Spekular should that be made in to a ticket ?

**Comment by Spekular** [comment]
> Looks like all issues mentioned here are addressed. Can this be closed ?

The linked issues are closed because they were consolidated into this one, but this doesn't mean that the bug or feature request is actually resolved. That's what the checklist is for, and looking at it one can see several unresolved issues remain.

**Comment by michaelgregorius** [comment]
Oops, sorry. I thought that I could watch the milestones using the dropdown. Instead it changed it for the issue.

**Comment by messmerd** [comment]
I've reopened all issues that were consolidated into this meta issue and marked as closed without actually being implemented. ([see this comment](https://github.com/LMMS/lmms/pull/7851#issuecomment-3621573077))
