### ISSUE TITLE
Arpeggiator overhaul

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#3880]
Some issues with the arpeggiator and the note sorting algorithms.

If you play an arpeggio over one note only things generally work fine. There is the issue with occasionally dropped notes but if you use the function to skip notes and only arpeggiate over one note at a time, there is a chance that you will experience not a single glitch. If however you choose to arpeggiate over a chord, then you will most likely bump into a couple of the following issues.

---

 - [ ] Skipped/extra notes. Sometimes notes are skipped or extra notes are sounding. Such an extra note can be the same as the actual note intended, increasing its volume.

 - [ ] The notes are only sorted after position and not after key. This is apparent in the arpeggiator when you're trying to arpeggiate over more than one key. It's difficult to get the notes to follow a defined route.
Proposed fix: 3862cfe3d1346e11a6dc5dff44b1e8a9b21b1bb5

 - [ ] The order of notes handed to the arpeggiator is inverted. If you're arpeggiating over more than one note the starting point is the highest note and direction down. This is probably a unique response for lmms as the usual is to start from the lowest one and walking up from there. Maybe an option to switch direction?
This may be a regression but because of all the other issues in the arpeggiator at the earlier version it's difficult to test properly.

 - [ ] Sorting notes is made both in `Pattern::addNote(...)` and in `Pattern::rearrangeAllNotes()`. The former is triggered on key 'on' and the latter on key 'off' but also works more generally on actions in the PianoRoll. The sort in `Pattern::addNote(...)` may thus be unnecessary. I've tested to drop this code and it seem to work just fine. Notes recorded through Midi keyboard are sorted only through Pattern::addNote so some rework seem to be needed to use `Pattern::rearrangeAllNotes()`.
Test: 84abaae3d31bffe07191f2a80bed9cab32111bc1

 - [ ] Pressing an existing note in the Piano Roll plays it back. When you release the key this triggers a note sort via `Pattern::rearrangeAllNotes():` the same way as a drag/shift action. This even though nothing really has changed to the pattern. It may be a non issue as the extra cpu cycles involved doesn't appear to be screaming high.

-  [x]  Sort mode. All notes are playing at the beginning of the notes. This is a regression from 1.1 and was introduced in 6650dd356dbdd08739ad69153b0c7020e39787b9.
Fixed in 2d583db990385506bff7020f4b4109976af5835f

-  [x]   Sort mode. If the envelopes are off, the notes that should be silent are playing as ordinary notes while waiting for their turn. Solving this by using the same hack as the 'skip' algorithm as it had the same issue.
Set as master note.
Fixed in 6da87379b4b5e69561a424ea13e604c7f077526c

Proposed functions
 - [ ] Strict sync. Follow the quantized positions and don't play notes on key 'on'.

**Comment by Spekular** [comment]
Feature Request: Ability to convert an arpeggio played by the arp function to notes in piano roll.

**Comment by zonkmachine** [comment]
> Ability to convert a pattern played by the arpeggiator to notes in piano roll.

Added.

**Comment by musikBear** [comment]
Feature Request:
Allow notes to have different delay effects in the arpeggio. This is known from f.i. Oatmeal and Synth1 and is awesome

**Comment by musikBear** [comment]
>  Ability to convert a pattern played by the arpeggiator to notes in piano roll.

How about the other way around -Eg building a pattern in piano-roll, including different note-length, pos, and velosity, and have that pattern exported to midi/ xml, and have arpeggiator able to import these *arp-templates* (partly known from FLs, but there is no edit-tool i know of)

**Comment by zonkmachine** [comment]
> Allow notes to have different delay effects in the arpeggio

As in delaying the note, like shuffle,  varying the amount of signal to a delay unit?


> building a pattern in piano-roll, including different note-length, pos, and velosity, and have that pattern exported to midi/ xml, and have arpeggiator able to import these arp-templates (partly known from FLs, but there is no edit-tool i know of)

There is something called groove templates which are midi snippets that you can use to force the timing on a track. Ps. Did you see this PR https://github.com/LMMS/lmms/pull/3117 ? Check out the last video at the [bottom post](https://github.com/LMMS/lmms/pull/3117#issuecomment-279137755).

**Comment by musikBear** [comment]
>  Did you see this PR #3117 ?

@zonkmachine wooo that vid is impressive 
It is not what i talk about though. I mean *delay* like in *echo*, but infact it is the velosity that changes.
I made a tut on how to build these 'velosity'-baselines, manually -Because that is possible!
https://www.youtube.com/watch?v=i_SQdvCzhhU
In **Oatmeal** he has an array of notes that can go into a sequenser (amazing VST btw, but very confusing)
In Synth1, there are different velosity templates, for the arpeggio, and it is awesome, but everything depends on the same velosity changes, that i  makes in the vid.
The FLs feature i thought of are patterns that can be imported on a simple arpeggio with the option 'file' - I believe the groove-patterns are much later addition to FLs ..i think my trial version is 6 so it is *ancient* :p

**Comment by zonkmachine** [comment]
Got it! Trying it out now and it grooves. Actually, I'm pretty sure #3117 can produce this already.

**Comment by musikBear** [comment]
@zonkmachine 
> I'm pretty sure #3117 can produce this already.

**Comment by zonkmachine** [comment]
> If that is added in 1.2x(+) then grooves ao arp seq can be saved and imported!
> (i often do my best work in bed..)

I don't think any more functionality like this is going to be in 1.2 . The first 1.3 RC should be out not long after 1.2 though., as I've understood it. As to your other ideas I've added 'temples' to the list for now. I'll look into the rest later.

**Comment by zonkmachine** [comment]
I think now pretty much all regressions from 1.0 should be fixed. The last long standing issue now is the issue with skippe/doublet notes which is currently held back by https://github.com/LMMS/lmms/issues/2606 . It's probably the same issue though.

**Comment by zonkmachine** [comment]
I've split the duplicate/skipped notes into two separate tickets. The duplicate notes come from note lengths being calculated wrong causing extra space at the end for a new note to be generated.

**Comment by zonkmachine** [comment]
Proposed fix for the 'extra notes' here: https://github.com/LMMS/lmms/pull/5523

**Comment by pkillnine** [comment]
Ideally there would be a way to be able to change the arpeggio chord for each note inside the piano roll. Currently you can only set one chord per instrument.

**Comment by pkillnine** [comment]
> @pkillnine
> 
> > Currently you can only set one chord per instrument
> 
> No you can play chords with arp, if you do it like this:
> https://www.youtube.com/watch?v=qBN6Hjom6S0

That's helpful thanks, but still quite clunky. If you could set a single note to play a particular chord pattern as an arpeggio, then it would be easier to experiment with different chords in the piano roll interface.
