### ISSUE TITLE
MSVC support

### ISSUE THREAD

**Issue by lukas-w** [LMMS/lmms#3999]
Creating this issue to keep track of tasks required to make LMMS build compatible with MSVC (related to #3492). I'll try to keep this list up to date:

- [ ] LMMS core code & CMake: I have most of the necessary fixes locally, will open a PR soon
- [ ] Plugins that fail building:
  - [ ] LadspaEffect
  - [ ] Monstro
  - [ ] Organic
  - [ ] ReverbSC
  - [ ] SID
  - [ ] VST
  - [ ] Vibed
  - [ ] Xpressive
  - [ ] ZynAddSubFX 

Because Windows provides no package management that we can use for grabbing dependencies, we'll need to find another way of making the overall build process easier. I suggest using [Hunter](https://github.com/ruslo/hunter) for fetching dependencies. Hunter is a package manager written using CMake, so if we leverage that, Windows devs will only need MSVC and CMake to get started. Unfortunately, most of LMMS's dependencies are still missing from Hunter, so we'll need to submit packages upstream. 

Dependencies include (not a complete list):

- [ ] For LMMS core:
  - [x] Qt
  - [ ] FFTW3: Fourier Transformation library
    * Website: http://fftw.org/
    * GitHub: [FFTW/fftw3](https://github.com/FFTW/fftw3)
    * Hunter issue: https://github.com/ruslo/hunter/issues/1160
  - [ ] libsamplerate: Used for resampling
    * Website: http://www.mega-nerd.com/SRC/
    * GitHub: [erikd/libsamplerate](https://github.com/erikd/libsamplerate)
  - [ ] libsndfile: Used for decoding and encoding audio files
    * Website: http://www.mega-nerd.com/libsndfile/
    * GitHub: [erikd/libsndfile](https://github.com/erikd/libsndfile/)
    * Hunter issue: https://github.com/ruslo/hunter/issues/1218
  - [ ] Audio backends:
    - [x] SDL2
    - [ ] libsoundio:
      * Website: http://libsound.io/
      * GitHub: [andrewrk/libsoundio](https://github.com/andrewrk/libsoundio)
    - [ ] PortAudio
      * Website: http://www.portaudio.com/
    - [ ] Jack?
- [ ] For plugins:
  - [ ] ZynAddSubFx
    - [ ] FLTK:
      * Website: http://www.fltk.org/index.php
  - [ ] Carla:
    * GitHub: [falkTX/Carla](https://github.com/falkTX/Carla/)
  - [ ] SF2:
    - [ ] FluidSynth:
      * Website: http://www.fluidsynth.org/
      * GitHub: [FluidSynth/fluidsynth](https://github.com/FluidSynth/fluidsynth)
  - [ ] Gig:
    - [ ] libgig:
      * Website: https://www.linuxsampler.org/libgig/

**Comment by tresf** [comment]
I've been putting some time into investigating `scoop.sh` for dependencies.  So far we have a working example of [`libsndfile`, `fftw`](https://github.com/lukesampson/scoop-extras/pulls?utf8=%E2%9C%93&q=+is%3Apr+author%3Atresf+) and I'm working with upstream on [`libsamplerate`](https://github.com/erikd/libsamplerate/pull/24#issuecomment-352308672).

Scoop's strategy is to use working-binaries of projects and just fetch them and put them in the user's home directory (e.g. `~/scoop/apps/libsndfile/current/`).

We've successfully made `cmake` and `pkg-config` locate these libraries:
 * cmake:  We're adding the relevant library folder to environmental variable `CMAKE_PREFIX_PATH`
 * pkgconfig:  We're adding the relevant library folder to environmental variable `PKG_CONFIG_PATH`

I propose `scoop.sh` as an alternative to Hunter, as the syntax is similar to `apt-get` or `homebrew`.

```ps1
# mockup
scoop install libsndfile fftw libsamplerate
```

The disadvantage of this approach over CMake is the majority of the dependency mirrors need to be created and maintained.

**Comment by lukas-w** [comment]
I think Vcpkg is the best candidate at the moment. I updated the issue accordingly. I'll change the wiki instructions to vcpkg as well if you don't mind, @tresf.

**Comment by tresf** [comment]
>  I'll change the wiki instructions to vcpkg as well if you don't mind, @tresf.

If it works, 👍.  Does `vcpkg` have any pre-built binaries, or is it all downloaded and compiled?  `vcpkg` is going to be less reliant on us maintaining packages all the time, but will likely add much more time to the compilation process.

**Comment by lukas-w** [comment]
> Does vcpkg have any pre-built binaries, or is it all downloaded and compiled?

Unfortunately, no. Mixing official Qt binaries together with libraries provided by vcpkg appears to work fine though.

**Comment by Cangle50** [comment]
To make it easer to follow is it possible to update LMMS compiling instructions for Windows MSVC to better show how we should do it by today’s standards.

My concern is that my Security Suite when navigating to the msys2 download site to install the Mingw-w64 compiler (that the QT5 Qt Creator IDE doesn’t appear to provide) is blocking me. 


![msys2blocked](https://user-images.githubusercontent.com/43626250/50787910-666ad480-127d-11e9-8349-87e5caf81126.png)

Some questions I have are.

Is msys2 still safe to use?

Is Qt 5.12.0 the best version to use right now, there appears to be a Drag and Drop issue with QT5?

Is it possible that the compatibility for Windows MSVC has gotten better, so that statements like "Warning, MSVC building is still experimental? Use with caution. Most plugins aren't available when compiling with MSVC" are no longer necessary? It feels as if we are encouraged not to use Windows MSVC for whatever reasons imho.

I am trying to teach myself how to write code and would like to use LMMS to study and learn from I realize that I have a long way to go. 

Things I have done.

1. Installed Visual Studio 2017 Community.

2. Installed Qt Open Source version 5.12.0 64/32bit with Qt Creator.

3. Installed CMake.

4. Installed Git.

5. Installed Vcpkg. I am in the process of installing fftw3
   libsamplerate libsndfile sdl2         

I am working on a windows 10 64bit pc.

Sorry to ramble on I am writing this for myself and anyone else who maybe having problems following along.

**Comment by tresf** [comment]
> My concern is that my Security Suite when navigating to the msys2 download site to install the Mingw-w64 compiler (that the QT5 Qt Creator IDE doesn’t appear to provide) is blocking me.

I strongly recommend that you contact Spectrum and challenge this claim.  Msys2 is a great product.

> Is msys2 still safe to use?

Unless proven otherwise, yes.  Is it useful for compiling LMMS?  Mostly.  The build toolchain is very volatile so it's not recommended.  MSVC would be a much "pure" build system at this point.  Our msys2 toolchain has tools that are cloned from the Linux cross-compiler, so if you can get familiar using MSVC, please do it.

> Is it possible that the compatibility for Windows MSVC has gotten better, so that statements like "Warning, MSVC building is still experimental? Use with caution. Most plugins aren't available when compiling with MSVC" are no longer necessary?

It's still experimental, that part is true but the warning doesn't need to be as harsh.  The plugin support is getting better, so I've clarified that only some plugins aren't available with MSVC.

> I am trying to teach myself how to write code and would like to use LMMS to study and learn from I realize that I have a long way to go.

Please continue to provide your feedback with the build process.  For assistance, please use #techtalk channel on discord and we'll be happy to offer any help we can offer.  You're welcome to chime in on this channel with wiki inaccuracies and/or fixes.

**Comment by PhysSong** [comment]
I just noticed SF2 player and GIG player are still MSVC incompatible due to VLAs.
https://github.com/LMMS/lmms/blob/29c210128a18fc48fe9771ae3b33b1eab7b0f92a/plugins/sf2_player/sf2_player.cpp#L634-L635
https://github.com/LMMS/lmms/blob/29c210128a18fc48fe9771ae3b33b1eab7b0f92a/plugins/GigPlayer/GigPlayer.cpp#L451
https://github.com/LMMS/lmms/blob/29c210128a18fc48fe9771ae3b33b1eab7b0f92a/plugins/GigPlayer/GigPlayer.cpp#L468
https://github.com/LMMS/lmms/blob/29c210128a18fc48fe9771ae3b33b1eab7b0f92a/plugins/GigPlayer/GigPlayer.cpp#L540

**Comment by justnope** [comment]
I'm currently working on sf2player and libgig.

sf2player is as good as ready, currently I created separate header file for STACKALLOC, but in hindsight I think it's better if I put it in lmms_basics.h
https://github.com/justnope/lmms/commit/1fbd51f05cb6696da2f216ca7d7f3095fab791e9

gigplayer is also 90% finished. I can compile libgig and currently working with upstream to have those changes included. If that works out, I'll open a PR to vcpkg to include it there. Then you can do a `vcpkg install libgig` and it will be found by lmms cmake.
libgig msvc repo:
https://github.com/justnope/libgig/commits/msvc
lmms gigplayer branch:
https://github.com/justnope/lmms/commits/libgig

**Comment by Rossmaxx** [comment]
Here to tell you about #6758

**Comment by Rossmaxx** [comment]
Bump the checklist pls, and also the gig pr has changed to #7162

**Comment by tresf** [comment]
Some's happened in recent versions that has caused major regressions in VSTs on MSVC, in particular the plugin failing to load under certain circumstances:
* Users on Discord reporting no VST support under Windows 10 with MSVC builds
* [My testing](https://github.com/LMMS/lmms/pull/7987#issuecomment-3224871025) showing that there's no VST support under Windows 11 in a VM with MSVC builds
* [My testing](https://github.com/LMMS/lmms/pull/7987#issuecomment-3224871025) showing that bare-metal works for 64-bit VSTs on Windows 11, but not 32-bit VSTs

We're unsure of the cause, but I've opened a dedicated bug report for it here:
* #8049
