### ISSUE TITLE
Finish implementing sample-exactness

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#402]
As this was discussed in the mailing list, I'm putting this out here as a sort of overview on the topic.

The "Sample-exact controllers" option currently does nothing. The implementation is halfway finished, but it needs to be finished. It's probably impossible to implement this for LADSPA effects (or VST's), but it should still be implemented for native effects and instruments. 

What we need is to firstly allow the option of enabling sample-exact mode for playback as well as export. 

Then, when in sample-exact mode: 
-  [x]  Instrument vol/pan knobs get sample-exact input
-  [ ] Filter cutoff/resonance knobs possibly?
-  [ ] Effect frontpanel W/D knobs get sample-exact input
-  [x] Mixer faders get sample-exact input
-  [x] Plugin Controls

All of this is for after 1.0.0

**Comment by tresf** [comment]
Some progress on this:
 * Waveshaper #1803
 * LFO #1809
 * Dual Filter #1800
 * Bass Boost #1802

@curlymorphic @diizy what is the feasibility all of the features/location noted in the OP make the cut for 1.2?

-Tres

**Comment by curlymorphic** [comment]
I have Looked to see where sample exactness is implemented

-  [x]  Instrument vol/pan knobs get sample-exact input
-  [ ] Filter cutoff/resonance knobs possibly?
-  [ ] Effect frontpanel W/D knobs get sample-exact input
-  [x] Mixer faders get sample-exact input
-  [x] Plugin Controls

**Comment by Moth-Tolias** [comment]
shouldn't this be tagged under meta?

**Comment by tresf** [comment]
@Moth-Tolias it pre-dates the introduction of the `meta` tag to the tracker, but yes. Updated.
