### ISSUE TITLE
Remove global automations

### ISSUE THREAD

**Issue by diizy** [LMMS/lmms#403]
So we have this thing called global automations. Not many people even know about them. I've never used them in any serious project. They seem like yet another hardly-discoverable secret feature of LMMS. They work well enough though - you set an automation for a control and it works as if it's an automation track placed at the beginning of the project.

So what's the problem with them? Well... think about it: you add a global automation to a control. You draw the automation curve, close the automation editor... and your control now has a hidden automation track, one which is in no way represented by the UI, one which you can only access from the context menu of the control itself. 

This is not good UI design... it is not WYSIWYG, it is not discoverable, it is not ergonomic. It is a hidden UI feature. There's no visual representation of these automations anywhere apart from when you're actually editing them.

The idea of global automations is good, it's just not implemented in a very user-friendly way. I can see three ways of dealing with this:

1 - remove global automations. For backwards compatibility, load old global automations as regular automation tracks. 

2 - add another editor window (which is hidden by default) that displays all global automations as automation tracks - kind of like the BB-editor, but for automations only.

3 - add a switch to hide/display global automations in the song editor.

Each of these options has their ups and downs. 

I've marked this for 1.1.0.

---

Here are the steps for global automation removal as [outlined by PhysSong](https://github.com/LMMS/lmms/issues/403#issuecomment-506914758):
- [x] 1) Let MIDI import plugin use separate automation tracks instead of global ones (DONE [#5223](https://github.com/LMMS/lmms/pull/5223), [#6605](https://github.com/LMMS/lmms/pull/6605))
- [x] 2) Write an upgrade logic that removes global automation patterns from project files and replaces them with normal automation tracks (DONE [#5229](https://github.com/LMMS/lmms/pull/5229))
- [x] 3) Remove any related GUI menus (DONE [#5230](https://github.com/LMMS/lmms/pull/5230))
- [ ] 4) Remove the feature if needed

**Comment by badosu** [comment]
Can we decide between removing this feature or suggesting a mockup for an UI improvement?

I'd like to take a shot at this issue..

**Comment by PhysSong** [comment]
I found that the feature is confusing for many people, and the confusion results in bug reports. Thus, I'd like to either remove or deprecate this feature. My plan consists of those steps:
1. Let MIDI import plugin use separate automation tracks instead of global ones
2. Write an upgrade logic that removes global automation patterns from project files and replaces them with normal automation tracks
3. Remove any related GUI menus
4. Remove the feature if needed

Opinions and suggestions are welcome.

**Comment by musikBear** [comment]
I 100% agrees to this '1+2+3+4' plan !

**Comment by zonkmachine** [comment]
> 1 - remove global automations. For backwards compatibility, load old global automations as regular automation tracks.

As I understand it this was completed in https://github.com/LMMS/lmms/pull/5223 and https://github.com/LMMS/lmms/pull/6605.
Close?

**Comment by Veratil** [comment]
This isn't completed, only the first step is.

**Comment by Rossmaxx** [comment]
Since there are issues with priority order, veratil has suggested to move it out of 1.3 milestone.

**Comment by FyiurAmron** [comment]
My 5c: from what I see, in the XML, changing `type` from 6 to 5 and moving the `<track>` into `<trackcontainer>` magically makes global automation track visible and editable when reloaded. Maybe this could be the easy interim solution, simply to make global automation track freely visible and editable? It would solve
>your control now has a hidden automation track, one which is in no way represented by the UI, one which you can only access from the context menu of the control itself
>This is not good UI design... it is not WYSIWYG, it is not discoverable, it is not ergonomic. It is a hidden UI feature. There's no visual representation of these automations anywhere apart from when you're actually editing them.
, i.e. the main problem here.
It would actually be the
>2. Write an upgrade logic that removes global automation patterns from project files and replaces them with normal automation tracks
as proposed by @PhysSong - it wouldn't break backwards compatibility, it would simply mean all new version would load global automation on the normal, editable automation track, and save it likewise. No new saves with hidden `type 6` tracks would be created, but it would be still loaded as it is now. UI for the possibility of adding global automation would be gracefully hidden behind an option that would be disabled by default. No functionality would be lost, 100% BC maintained with full legacy UX support.

**Comment by Rossmaxx** [comment]
Good observation. I would like to see this getting implemented. If you would like, work on the implementation and I'll help you get this through.

Tbh I don't know much about the xml implementation so i ain't looking at it.

**Comment by Rossmaxx** [comment]
I just merged #5229, so the parts 3 and 4 remains.
