### ISSUE TITLE
Sample file locating improvements

### ISSUE THREAD

**Issue by lukas-w** [LMMS/lmms#4309]
Consolidating issues about sample file location or missing sample file search.

- [ ] Allow several sample paths (#2842)
- [ ] Search in project file's directory (#2982)
- [ ] Search for sample files with same name but different extension (#2825)
- [ ] Search on other storage devices (#4266)

As long we don't have support for sample bundling (#1257), we should store more information about samples in the project file to be able to locate them better. At the moment, we only store the file name & absolute path. Additional ideas:

* File size
* File hash
* Acoustic fingerprint (would help relocation even if the file was re-encoded)
* A flag indicating whether the sample is a factory sample shipped with LMMS
* Other metadata?

**Comment by CYBERDEViLNL** [comment]
I have a proposal. What about creating a option `Save as Portable Project` which does the following:

1. Open a dialogue that request a PATH and DIRECTORY_NAME.
2. Instead of creating a `.mmpz` file or alike directly, it creates a directory within the given PATH and with the DIRECTORY_NAME.
3. It copies all dependants (samples and soundfonts) into that directory (or subdirectories of that: `DIRECTORY_NAME/samples` and `DIRECTORY_NAME/soundfonts`).
4. It stores the normally created `.mmpz` in that directory as `DIRECTORY_NAME.mmpz` with relative paths to the samples and soundfonts.

We also need to add a entry to the `QDomDocument` to define that it’s a portable project so it knows if we add new samples/soundfonts that they should be stored relative also. Same goes for saving a portable project it should purge removed samples/soundfonts.

Duplicate filename scenario:

Used samples:
```
a/kick.ogg
a/snare.ogg
b/kick.ogg
b/snare.ogg
```

Would become
```
samples/kick.ogg
samples/snare.ogg
samples/kick.1.ogg
samples/snare.1.ogg
```

**Comment by musikBear** [comment]
In regard to *"LMMS should look for missing samples"* an intermedia option would be, that the user either input a direct path, and LMMS will then load that file, or user inputs a directory, and LMMS then scan that. The latter is used by sonys tracker sw.
Even thoug i am somewhat reluctant to let programs make HD changes, LMMS could either make a copy of the located file or *move* the located file, into the *Setting* defined path, so that this relocating would be a one off.
Writing this, i also see a design for **packed-projects**

**Comment by messmerd** [comment]
I've reopened all issues that were consolidated into this meta issue and marked as closed without actually being implemented. ([see this comment](https://github.com/LMMS/lmms/pull/7851#issuecomment-3621573077))

**Comment by lukas-w** [comment]
These issues are all improvements to the same feature (sample file searching) and IIRC all affect the same code. So the intention here was to allow a general discussion about how this feature should improved, and to make developers aware of all issues because it may be easier to solve several at once in one rewrite instead of re-working the same code multiple times by doing them one-by-one.

Citing https://github.com/LMMS/lmms/pull/7851#issuecomment-3621573077:

> The issues listed there were marked closed as completed [...]
>  I think in hindsight this practice was a _very_ bad idea since everyone (including you) gets the false impression that bugs were fixed and features implemented when they have not

Before passing harsh judgements in hindsight, you may also want to be aware of the more limited features in GitHub's issue tracker back then. There was no support for issue (parent) relationships and there was no way to specify the reason for closing an issue (GitHub marked all old issues as "completed" when introducing this feature).

**Comment by messmerd** [comment]
> These issues are all improvements to the same feature (sample file searching) and IIRC all affect the same code. So the intention here was to allow a general discussion about how this feature should improved, and to make developers aware of all issues because it may be easier to solve several at once in one rewrite instead of re-working the same code multiple times by doing them one-by-one.

I just set this issue as the parent issue for those issues, so that should point people here.

> Before passing harsh judgements in hindsight, you may also want to be aware of the more limited features in GitHub's issue tracker back then. There was no support for issue (parent) relationships and there was no way to specify the reason for closing an issue (GitHub marked all old issues as "completed" when introducing this feature).

That makes sense. Thanks for shedding light on that, and sorry if I came off as overly harsh.

**Comment by lukas-w** [comment]
> I just set this issue as the parent issue for those issues, so that should point people here.

Thanks!

**Comment by lukas-w** [comment]
> Thanks for shedding light on that, and sorry if I came off as overly harsh.

Sorry if I came off as overly sensitive :) Didn't exactly have the best of days when I wrote that.
