### ISSUE TITLE
Equalizer: Better spectrum display

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#4395]
Current EQ has a spectrum display. It is nice, but it can be improved a lot. Here are some of possible enhancements:
- [ ] Allow changing visible range of audio level #3624
- [ ] Allow changing window function #3625
- [ ] Allow changing buffer size #3626
- [ ] Add more stereo linking method(RMS, maximum, etc.)
If you have some good ideas, please let us know!

**Comment by SecondFlight** [comment]
Enabling antialiasing would likely be a simple way to improve the look of it. It's incredibly easy to do, you just tell Qt that you want antialiasing. You ought to be able to Google for how to do it, I don't remember off the top of my head. You can also go to the code for my latest waveshaper PR and search for antialiasing.

**Comment by DouglasDGI** [comment]
> If you have some good ideas, please let us know!

I'd say it would be a good idea to have the option to display the left and right channels simultaneously in different colors.  Then one could easily compare the difference in frequency content between ears.

**Comment by messmerd** [comment]
I've reopened all issues that were consolidated into this meta issue and marked as closed without actually being implemented. ([see this comment](https://github.com/LMMS/lmms/pull/7851#issuecomment-3621573077))
