### ISSUE TITLE
Ghost notes improvements

### ISSUE THREAD

**Issue by zonkmachine** [LMMS/lmms#4796]
- [x] Currently the option to set as ghost pattern isn't presented in the pattern context menu for a pattern that is currently selected. You may want to create a pattern as a main theme, set it as ghost pattern and then go about and work on other patterns but currently this is not possible. You need to create at least one other pattern first and then set the first pattern as ghost pattern via the context menu.

I believe this may be the only line involved here and I suggest removing it: https://github.com/LMMS/lmms/blob/5126070bb1494d81f9efc9188594a80b6574a466/src/tracks/Pattern.cpp#L680

 - [x] The ghost pattern isn't remembered when saving a project. You probably wan't this so you can continue working precisely where you left off when you load a project next time.

_Edit: From comment [below](https://github.com/LMMS/lmms/issues/4796#issuecomment-460798803)_
 - [x] When first loading a project the Piano Roll has no pattern loaded. There will be no option to set any pattern as ghost, even though the patterns are visible, until a pattern has been opened.

 - [x] It looks better to show the `setGhostInPianoRoll()` menu option all the time and setting it inactive (greyed out) when there is no pattern.

@CYBERDEViLNL

**Comment by CYBERDEViLNL** [comment]
On the first issue: just removing that line will not give you the expected result since the ghost pattern is a pointer to a pattern. So if you put the current pattern as a ghost it will only result in the ghost pattern drawn behind your current pattern (not visible) and if you edit the current pattern so will the ghost, so no point in that. In order to achieve the behaviour as you described we need to copy a pattern instead of point to it. If this is really desired I am willing to look into that.

On storing the state, this should be do-able. But this isn’t only a ghost note issue? Here when I create/open a pattern in the Piano-roll, then save the project, close LMMS, open LMMS and load the project again: the Piano-roll is empty. Can you confirm that?

**Comment by zonkmachine** [comment]
> Here when I create/open a pattern in the Piano-roll, then save the project, close LMMS, open LMMS and load the project again: the Piano-roll is empty. Can you confirm that?

Yes. You need to first load a pattern by double clicking it. You don't need to restart LMMS. Just load another project or a new one and the Piano Roll will be cleared. If this is what you meant.

**Comment by CYBERDEViLNL** [comment]
Yes that is what I meant. I think I misinterpreted the issue. Is this what you mean by remembered?

1. Set ghost pattern.
2. Save project.
3. Reopen project.
4. Open a pattern.
5. Now the ghost set in step 1. should be present.

**Comment by CYBERDEViLNL** [comment]
Ok great that’s clear :-) 

Then we have to loose the pointer, make a copy of a `NoteVector` `m_notes` instead of pointing to a pattern. This will address both issues. If there’s no rush I’m willing to work on that.

**Comment by zonkmachine** [comment]
> If there’s no rush I’m willing to work on that.

There's no rush. Please work on that. ;)

**Comment by zonkmachine** [comment]
A couple of things strike me while testing https://github.com/LMMS/lmms/pull/4812 (which works well so far).

 * When first loading a project the Piano Roll has no pattern loaded. There will be no option to set any pattern as ghost, even though the patterns are visible, until a pattern has been opened.

https://github.com/LMMS/lmms/blob/9ec7cc83d543d84816b2eb516eeb5a560a0d762d/src/tracks/Pattern.cpp#L679
This is a bit confusing. I find it a bit less confusing to open the Piano Roll even without a pattern instead of not showing the option in the context menu. I'm trying this without the `gui->pianoRoll()->currentPattern()` test and like this more. Are there problems removing this other than the oddity of a blank Piano Roll opening? The pattern is set properly anyway. Maybe the Piano Roll should also remember and load the last pattern in the project?
* It looks better to show the `setGhostInPianoRoll()` menu option all the time and setting it inactive (greyed out) when there is no pattern.

**Comment by CYBERDEViLNL** [comment]
Removing the `gui→pianoRoll()→currentPattern()` check shouldn’t cause any troubles other then indeed the blank Piano-Roll opening.

I’ve made some changes to https://github.com/LMMS/lmms/pull/4812 :-)

**Comment by zonkmachine** [comment]
> I’ve made some changes to #4812 :-)

Spot on! 8)

**Comment by zonkmachine** [comment]
OK. Updated the issue to reflect what's been covered here. That's enough of fixes for one issue I think. Calling this 'Job well done!' and closing.

Thanks for working on this!

**Comment by PhysSong** [comment]
@CYBERDEViLNL I found one more bug. Steps to reproduce:

1. Create a pattern and add some notes
2. Set the pattern as the ghost pattern
3. Open the pattern and move a note
4. You can see a ghost note where the moved note was

It's okay if it's intended and acceptable, though.

**Comment by CYBERDEViLNL** [comment]
Hello @PhysSong  , thanks for noticing. This is a side-effect with https://github.com/LMMS/lmms/issues/4796 since the notes used as ghosts are now copied instead of pointed to. As far as I can see there is not really a way around it without giving each pattern it’s own unique ID. I also find it acceptable and can be a feature too :-P If people experience this as a bug then please let me know.
