### ISSUE TITLE
Better Workflow

### ISSUE THREAD

**Issue by tresf** [LMMS/lmms#4877]
I'm creating a meta issue for better UI/UX workflow.  This list should be updated frequently because it's the source of many of our new bug reports.  If a new bug report arrives that seems workflow related **AND won't be closed by a quick patch** it can be marked as a duplicate and placed here.

Since workflow is so important to users -- something they can directly relate with -- this can also help serve as a futuremap if the developer team is to start milestoning certain enhancements (something we don't do a great job of currently)

Lastly, it can serve as a birds-eye-view (so to speak) of what our users really want. ❤️ 

💥 = Bug
🚀 = Good first issue for new developers

See also:

## Tracks
* #### Song Editor/Beat+Bassline Editor
   * [ ] Better transport/playback/playhead behavior
      * [ ]  Position indicator and line behavior inconsistent between Song-Editor, Piano-Roll, Beat/Bassline and Automation Editor #857, #2123, #3052
      * [ ] Global playback/transport #1357
      * [ ] Project should remember the last-used playhead behavior per #4192, #4556
      * [ ] Better keyboard shortcut behavior when mixer is in focus #1140 (related: #1488)
      * [ ] Better keyboard shorts in general #1144 (related: #1488)
      * [ ] Proposal to use `>>` as default playhead behavior #3740
      * [ ] Stop and return `|<<` versus "pause" default behavior #3740
      * [ ] Link JACK transport with LMMS transport #4412
      * [ ] Stop button should stop ALL sounds #1535
      * [ ] Playback should stop at the end of a track #4643
   * [ ] Better track color support #1006 #1160 #1176 #2332
   * [ ] Rename Song Editor/Beat+Bassline Editors #121
   * [ ] Add Beat/Bassline pattern previews #4845
   * [ ] Ability to cut/join patterns in the sequencer #3829 #3633
   * [ ] Show mixer channel on each instrument #2563
   * [ ] Volume control on individual B&B tracks #2218
   * [ ] Disabling or changing the Song Editor's Bar Grid #2171 
   * [ ] 🚀💥 Wrong cursor when moving blocks in song editor #879
   * [ ] Stretch/Shrink/Shorten Patterns via SongEditor #1658 
   * [ ] Inconsistent/confusing toolbar layout #4829
   * [ ] Better workflow when adding BB #2014
   * [ ] Annotations/markers/bookmarks #156 #380
   * [ ] 🚀 Open pattern to specific bar #3305
   * [ ] Vertical Zoom in Song Editor #3763 
   * [ ] Pre-delay/leading track support #87 
   * [ ] Song editor group operations #1212 
* #### Piano Roll Editor
   * [ ] Better placement of pasted notes #4836 
   * [ ] Add "quick clone" of notes #3015 (related #1844)
   * [ ] Ability to cut/join patterns in the piano roll editor #746 
   * [ ] 🚀Setting velocity on left-most note accidentally clicks changes to pan (similar to #4860)
   * [ ] Draw note length in Piano Roll #3101
   * [ ] Highlighting note lines with color #3027
   * [ ] Vertical Zoom Support in Piano Roll #2294
   * [ ] 💥 Note automation in pianoroll is over Panning/Volume bar #1156
   * [ ] In piano roll view, change to another track without losing the time position #2093
   * [ ] Make step sequencer step size configurable #4823
   * [ ] Faster chord creation #4361 #4079 #3673 #615
   * [ ] Add a button to enable a piano-roll TCO #4209
   * [ ] Finer note pitch bend precision #4234
   * [ ] Pitch bend recording directly to piano roll #3724
   * [ ] Note "pattern" builder #688
   * [ ] Note "humanization" #1165 
   * [ ] User added scales. #241
* #### Automation Editor
   * [ ] 🚀Hard click/select zero/bottom of automation editor #4860 
   * [ ] Support for automation presets #119
   * [ ] Improved Vertical Zoom in Automation Editor #4313 
   * [ ] Connect to multiple Automation TCOs simultaneously #4132
   * [ ] Ability to have both curved and straight lines in Automation Editor #4097

## Instruments
* #### Internal
   * [ ] **New**: Add a new drum pad instrument #4877
   * [ ] **AudioFileProcessor**: Allow sample loading from OS' drag-and-drop #2120 
   * [ ] **AudioFileProcessor**: Pitching/librubberband support #1734
   * [ ] **SampleTrack**: Better SampleTrack support #1471 ( `meta` )
   * [ ] 🚀 **All**: Some instruments are too loud by default #113
   * [ ] Instrument plug-ins tab memory. #3646
   
* #### External
   * [ ] Make frequently used VSTs easier to access #4853 

## Mixer and Effects
   * [ ] Rename "FX Mixer" to "Mixer" #3300
   * [ ] 🚀 Pan knob #1974
   * [ ] Wet/dry knob #4403 
   * [ ] Input gain control #118
   * [ ] 🚀`dB` indicators #1213 4458
      * [ ] Snapping/faster/better fader/slider #3098
      * [ ] Better default fader/slider location #3253
   * [ ] Better default meters in mixer #75
   * [ ] Mixer/channel presets #1680
      * [ ] Mixer/channel templates #4023
   * [ ] Support multiple selections #4644
   * [ ] Drag & drop track assignment #2011 #3150
   * [ ] Drag & drop reordering #605 #4655
   * Better visual indication of assignment
      * [ ] Show channel assignment on Song Editor #2563
      * [ ] Connections for selected instrument #1216
      * [ ] Channels with no connection at all #1224
      * [ ] Assignable (or automatic) color support #1665 #2704
      * [ ] More intuitive routing #1823 #4187
      * [ ] Routing overview/dedicated window #1986 #3294 #4181
      * [ ] Auto-sort option #605
      * [ ] Grouping #606 #4402 #4650 #4644 
      * [ ] Option to show title instead of channel #3239
      * [ ] Remove tooltips #3257
   * [ ] 🚀Consistent wording/icons #3242
   * [ ] Make the EQ plugin resizable #1904 #3258 #4644
   * [ ] 🚀Clone/Duplicate Effect #1278
   
## Files and Folders
   * [ ] Make "My Home" user definable in settings #1130
   * [ ] Arrow keys should preview samples in the file browser #871
   * [ ] 🚀 Refreshing the File Browser should not collapse all folders #2121
   * [ ] Default VeSTige File? #434
   * [ ] Better Save As/Open/Browse Dialog #1834

## Misc/Overall

**Comment by musikBear** [comment]
Add ? 
* Annotations on timeline  #380 (aka bookmarks) 
* Open pattern to specific bar from song editor #3305

**Comment by tresf** [comment]
There's literally hundreds of bug reports, no need to comment on each one.

**Comment by qnebra** [comment]
I think this https://github.com/LMMS/lmms/issues/4554 is very, very related to this topic. Especially for lmms users with external controllers like me. 

Because for now lmms workflow with external controllers isn't as good as it should be.

**Comment by tresf** [comment]
@qnebra that sounds like a legitimate bug.

**Comment by tresf** [comment]
@qnebra you sent me a PM on Discord and I want to be more clear.  Your bug affects workflow (all bugs do), but it's not a "nice to have" feature, it's a legitimate bug and should be tracked as such.

Quoting the bug you've linked:

> it works, only if you disconnect "volume" from "mod wheel".

I want to keep the bugs open in our tracker so that they're easier for developers to find, assign and work on.  The features above are related to items -- in most cases -- completely missing from LMMS and are better left in a `meta` issue so that there's a bird's eye view of demand and related issue.  I hope that helps!

**Comment by claell** [comment]
@tresf I like the idea of having meta issues (although tags might also do a good job for this particular problem), but the current way of doing this does not look "right" to me. Why close issues linked here and mark them as duplicates? The "normal" way I am used to is to use labelling to distinguish between feature requests and bugs, so they can coexist in an issue tracker and are only closed when implemented.

**Comment by tresf** [comment]
> @tresf I like the idea of having meta issues (although tags might also do a good job for this particular problem), but the current way of doing this does not look "right" to me. Why close issues linked here and mark them as duplicates? The "normal" way I am used to is to use labelling to distinguish between feature requests and bugs, so they can coexist in an issue tracker and are only closed when implemented.
> 
> Edit: Seems like I misunderstood things a little bit, thought all issues linked here are closed.

I'm not aware of another way to cleanup 800 bug reports.  Even with the above 100 bug reports, there are still over 600 still open.  Notice many already have 2, 3, or 4 duplicates!  Other projects (like Ubuntu) simply blindly close out bug reports when they EOL a product, I feel this technique is better and I hope this approach is better received.

Moving forward, we'll have better bug submission standards which should help avoid duplicates as well as encourage people to open PRs instead of bug reports for minor changes.

**Comment by claell** [comment]
Hm, maybe I am just not really understanding what this is for.

In general my opinion:

If these 800 bug reports / feature requests are actually not solved already then they shouldn't be closed, but maybe they are solved already or not relevant anymore. But maybe they are so "small" that it is not worth to have issues for every single one of them.

I guess the real problem is that on the development side there is too less "power" to keep up with the speed of new issues appearing.

> there are still over 600 still open that we need to sort through

Maybe a better tagging can be used (or leave them open). I am not a fan of closing not solved issues, but maybe that is the most effective way.

> Other projects (like Ubuntu) simply blindly close out bug reports when they EOL a product, I feel this technique is better and I hope this approach is better received.

Maybe I misunderstood this a bit, but I think there is nothing EOL here?

Still better than blindly closing things, so thanks for taking the effort to go through all these issues.

**Comment by tresf** [comment]
> Maybe I misunderstood this a bit, but I think there is nothing EOL here?

Neither is there (EOL) with Ubuntu, that's the point.  Most trackers force bug submitters to file against a "supported" OS version and then close them out blindly (no human review at all) when the OS reaches EOL. Many trackers do this.  Trackers like JIRA can do this and they put the burden back onto the submitter (they notice the bug was closed incorrectly, they have to reproduce and re-file).

The problem with LMMS isn't the bugs though, it's actually the enhancements.  The bug tracker is being misused as a wishlist and for a product with only a few maintainers and over 2 million users, this is a problem.  Rather than tracking these requests as "open" it's more honest to ourselves to focus on what the project needs first.

For example... Take this rant into consideration... I'm typing this RIGHT NOW just off the top of my head... 

> The playback position head of a track sucks.  The stop button should jump back to beginning, always!The pause should ALWAYS PAUSE, NOT STOP.  The cursor should be consistent across ALL editors.   Why isn't there a cursor in the Beat/Bassline editor?  Why can't I click "pause" from the mixer?  Why isn't there a visual indicator of the channel the track I'm working on is routed through?

These issues are fundamental flaws (or limitations) with the UI and the inconsistencies introduced over years and years of volunteer work.  They were never design choices, but they can, will and have spun into dozens of bug reports all pretty much stating "do it like Ableton does" :)

Our permanent solution is to provide very strict submission guidelines (with a separate template for enhancement and bugs).

> I am not a fan of closing not solved issues, but maybe that is the most effective way.

The first step to cleaning up junk is to put it in a big pile and decide what to throw out.   That's what we're doing and we need help. :)

**Comment by claell** [comment]
> Neither is there (EOL) with Ubuntu, that's the point. Most trackers force bug submitters to file against a "supported" OS version and then close them out blindly (no human review at all) when the OS reaches EOL. Many trackers do this. Trackers like JIRA can do this and they put the burden back onto the submitter (they notice the bug was closed incorrectly, they have to reproduce and re-file).

I haven't experienced this with bugs on Ubuntu, so I don't really understand what you mean, but I guess it is not that important.

> misused as a wishlist

Well, of course you can decide what to use the issue tracker for, but in most projects the issue tracker is actually used as a wishlist without problems. I wouldn't speak of a misuse in that case. This just results in many open issues, but there is nothing bad about that imho, because you can filter for bug tagged issues.

> Rather than tracking these requests as "open" it's more honest to ourselves to focus on what the project needs first.

Imho focusing can be done without closing them.

> Our permanent solution is to provide very strict submission guidelines (with a separate template for enhancement and bugs).

Sounds reasonable. I created #4889 to create them.

**Comment by tresf** [comment]
> I created #4889 to create them.

Thanks.  @lukas-w already created a PR for this.  Can you provide your assistance there so that it's centralized?  Also, please search before creating new issues. 😉 

> Imho focusing can be done without closing them.

... and do what exactly?  Pick a "good" bug, paste the other ideas into it and make it appear like it was written by the OP?  We've been doing this right along and it's actually worse.  The pruning is happening and it's going to make the tracker easier for the developers.  If there's one that really needs reopening, please request it.  Ideally, we'd have more people helping with these in general but they require a holistic understanding of the software, which is usually best corralled by a developer, tester, or power user.

**Comment by tresf** [comment]
>  but in most projects the issue tracker is actually used as a wishlist without problems

Not true.  Projects with a large user-base and low-quality submissions (like openjdk) just block end-users from submitting.

> I haven't experienced this with bugs on Ubuntu, so I don't really understand what you mean, but I guess it is not that important.

It may be a bad example but trackers do this, I just don't have an example, and I'm losing time to find one.

**Comment by claell** [comment]
> Also, please search before creating new issues.

I know, I know, only searched the issues, not the PRs :smile: 

> ... and do what exactly? Pick a "good" bug, paste the other ideas into it and make it appear like it was written by the OP? We've been doing this right along and it's actually worse.

Why is picking a "good" bug needed? Imho the workflow is the following:
* User creates a feature request
* Feature request gets labelled correctly and edited if problematic
* Result: Good feature request
* Duplicate feature request is opened, can be closed with reference to good feature request
* Maybe problematic and result of this meta issue: The second feature request is actually better or requests more functionality than the original one. Solution to this would be to either reduce the second one to the added functionality or indeed add the additional functionality to the first feature request, which *should* not cause problems, but I did not experience what you did, so that might be different in practical situations.
* Result: Many small feature requests, might get overwhelming, so put them in meta issues and / or use tagging

> Not true. Projects with a large user-base and low-quality submissions (like openjdk) just block end-users from submitting.

I said in *most* projects, in your example that might be true. So maybe we are both true in our points, while your point is probably more relevant.

> It may be a bad example but trackers do this, I just don't have an example, and I'm losing time to find one.

No problem.

**Comment by tresf** [comment]
> Many small feature requests, might get overwhelming, so put them in meta issues and / or use tagging

This bug report is a step in that direction.  We've already closed about 100 bugs.  We need to do 600 more and then we can talk about how big this mess is and what to with new meta issues moving forward.  We're reading every bug report in the process and trying to find a home for it.  Many of these bugs were opened by developers, and they're OK with this too.  Cleanup always looks worse before it looks better. :)

**Comment by claell** [comment]
Yes, but I meant *without* closing them :smile: 

Reasons for leaving them open:
* There will be probably be discussion there if a developer decides to implement a feature from this list
* That way the issues can also be found when going through open issues
* It just feels wrong to me to close not implemented issues with maybe relevant discussions

Cons:
* Maybe they seem to clutter the issue list, but that should not be a problem with tagging
* If the issues are kept open they might need some polish, but I think that is worth it and I am also offering my help with that

**Comment by tresf** [comment]
> There will be probably be discussion there if a developer decides to implement a feature from this list

We don't lock bugs, this can still happen.

> That way the issues can also be found when going through open issues

No one goes through 800 issues.  I agree it's hard to decipher open from closed, but that's solved in "what to with new meta issues moving forward" portion above.

> It just feels wrong to me to close not implemented issues with maybe relevant discussions

Agreed but as a maintainer, it feels worse to have a bug tracker that at its current growth rate will have thousands of bugs, many being duplicate or describing a feature that won't be coded for years to come.  It's misrepresentative of the contributors and the tracker is meant for developers.

**Comment by claell** [comment]
> We don't lock bugs, this can still happen.

I know, but usually closed issues aren't discussed that much.

> No one goes through 800 issues

I know but with decent tagging there won't be 800 issues to go through but only a few. For example if someone searched open issues with the tag starter.

> thousands of bugs

I don't see the difference of having them "pseudo"-closed or opened to this problem.

> many being duplicate

Than they can be closed?

> describing a feature that won't be coded for years to come

That is normal and should not be bad. Also I think one could introduce a tag for that to filter them out, if possible or put all relevant issues into milestones to get rid of "utopic feature requests" for the current development process.

> the tracker is meant for developers.

Should be the priority, but not only. And I really don't see what is improved for the developers when closing those issues in comparison to leaving them open. To me that is maybe only a psychologic effect.

**Comment by tresf** [comment]
> don't see what is improved [...] only a psychologic effect.

This is just more arguing of the same point.  The reasons are clearly outlined and explained.

**Comment by claell** [comment]
> The reasons are clearly outlined and explained.

Well as far as I know, you never really explained what is bad about open feature requests, also I elaborated, why they are not bad. But ok, you can decide and it actually is not that bad to close them, so I won't ask for explanation any further and accept that you want to have this in that way.

Still my offer for help stands. This will probably require to add me to the LMMS team, which might be a bit fast from your perspective. If you need any references, some sort of interview etc. let me know.

What I would do / propose is to go through the remaining open issues and assign feature requests with more detailed tags like `piano-roll`, `song editor`, `mixer and effects` etc. Those tags might not be perfect at start, but can be renamed or agglomerated in a later effort. That would allow you to filter through those tags in order to agglomerate those issues in this meta issue.

**Comment by tresf** [comment]
> What I would do / propose is to go through the remaining open issues and assign feature requests with more detailed tags like piano-roll, song editor, mixer and effects etc. Those tags might not be perfect at start, but can be renamed or agglomerated in a later effort. That would allow you to filter through those tags in order to agglomerate those issues in this meta issue.

Tags can help find a particular issue if that's what you're looking for, but they're not holistic.  Holistic coding requires knowledge of the codebase and corralling of issues.  With 800 issues falling into 10, 20 or 50 different categories, tags can become busy work that results in the same mess.

> Still my offer for help stands

Observed efforts are concerning.  For example, choosing to rename internal names/files (#4890, more work for developers).  Furthemore, making an organized effort to consolidate bug reports a home for endless conversation is detrimental.

**Comment by claell** [comment]
> Tags can help find a particular issue

Yes and they can also help sorting issues, find duplicates etc.

> but they're not holistic.

I don't understand what you mean with that.

> corralling of issues.

I'd be interested in a source for that statement.

> falling into 10, 20 or 50 different categories, tags can become busy work

Well, it will be work, but that work has to be done anyway. And regarding your continuous "mess" statements, have a look at

https://gitlab.com/gitlab-org/gitlab-ce/issues

and how they handle their bunch of issues.

> concerning

Sad to hear that.

> choosing to rename internal names/files

I asked @SecondFlight before, so please stick to the facts.

> a home for endless conversation has historically proven detrimental to productivity.

Again, please stick to the facts. I contacted you via Discord just because I did not like to discuss this in this GitHub issue. You told me the discussion should be continued on GitHub, here we go. I don't like how you now give this back to me and insult me like this was my fault.

> We can discuss more on Discord.

Alright.

**Comment by tresf** [comment]
> You told me the discussion should be continued on GitHub, here we go

No, I said "public".

> I asked @SecondFlight before, so please stick to the facts.

I'm not sure what this is in reference to.  Regardless, these types of `ad hominem` replies quickly become toxic.  Feedback about the renames were made in the relevant bug reports.

In regards to holistic and corralling, it's about overall view of the project (how it's progressed, how it will progress, what the necessary resources are to continue progressing).  It's about combining related items as well as... and this part is very important... the **unnecessary specificity of requests that are trivial** (i.e. Items that explain basic improvements that are common sense to any UI developer, just lack the hours and hours of coding, debugging and testing to roll into a future release.  Furthermore, items that have no intention to be worked on are pointless to be in "open" state.  Different projects have different opinions on this, but I'm not sure GitLab is a good example.  1.  They're commercial, we're not.  2. They have `33K` issues, one of which is that with that many issues, [searches result in a 500 error](https://gitlab.com/gitlab-org/gitlab-ce/issues/58899).  Ouch.

Anyway, we're not trying to discourage help, but spending this much time arguing the Open/Closed state of a bug that the project actually cares about is a classic example of Parkinson's law of triviality.

**Comment by Gabrielxd195** [comment]
This is great!!. Having all the problems listed and organized is the best. although I have been able to observe some even greater problems:

- There are many errors and improvements and the list is increasing.
- There are few collaborators and developers.
- All those improvements will require a great development time to implement them all.
- Each improvement will bring new errors.

Well, this is my humble opinion:

- Discuss more thoroughly which improvements are more urgent than others.
- Discuss which improvements will require more development time than others.
- Organize the improvements in order of priority.
- Do not accumulate too many improvements for a single release.
- Examine the stability of some improvements tested in '' master '' and if they are stable, merge them to '' stable ''.
- Create a goal with improvements for the next update, milestone 1.2.1.
- Do not accumulate too many improvements for 1.2.1.

Over time the list will increase and all this required a lot of time for its development. regards

**Comment by SecondFlight** [comment]
I appreciate your input, but please allow me to correct some of what you've said, as your premise is largely inaccurate:

`There are many errors and improvements and the list is increasing.`

Indeed, this is what the list is meant to help with. Our issue tracker is unbelievably bogged down, mostly with well-meaning enhancement requests. The primary goal of this list is to concentrate the mess into one place and allow us to close issues with lower priority. This list is getting bigger, but each time an item is added to this list, it is closed on the tracker.

`The improvements are being released in test versions (RC)`

This is not true. There have not been new features added to the release candidates in over a year. All changes to the RCs are bug fixes.

`The release of stable 1.2 was delayed.`

This is because there have been a lot of bugs worth fixing.

----

This list is **not** a list of must-have features that we plan to implement. This list simply represents an effort to clean up our tracker. Every feature on this list has been open in our tracker for some time, but the act of moving these features here doesn't mean we plan to implement all or even any of them.

**Comment by Veratil** [comment]
Not sure if this is the right place to comment for this, but I wanted to better organize, format, and generally prettify the Coding Conventions page for easier reading. Are we still wanting to have that page? I do see some other PRs now for clang-format and clang-tidy, but I'm not sure where things are going with it.

I did go ahead and make a [prettified version here](https://github.com/Veratil/lmms/wiki/Coding-Conventions-Prettified) (with extra stuff at the top to make sure I covered things) in case we want to update. I figured using RFC style requirement keywords would be best to describe what rules could be bent or not.

**Comment by tresf** [comment]
> Not sure if this is the right place to comment for this

Thanks.  It's not, really.

This thread is for software workflow (not developer workflow).  Probably better for the "how to keep programmers" threads.

The organization of topics in the new version is nice.  The capitalization and italics for words like *NOT* (does the RFC recommend this sillyness?) aren't needed (I don't even see this weirdness in license agreements, where there's legal action).  Anyway, the fact that you've taken the initiative to help the project means something to us, you can start editing it any time.  Just ping someone one #devonly on Discord for access, linking this comment.

**Comment by Veratil** [comment]
> > Not sure if this is the right place to comment for this
> 
> Thanks. It's not, really.

I was going to comment on the closed Coding Conventions issue, but I'm not sure how y'all like commenting on closed issues, and you stated from that one that this superseded it.

> The capitalization and italics for words like _NOT_ (does the RFC recommend this sillyness?) aren't needed (I don't even see this weirdness in license agreements, where there's legal action).

That was my choice, RFC only states they are "often capitalized". I wanted to put emphasis on them to make them stand out. It can easily be removed. 😁

> Anyway, the fact that you've taken the initiative to help the project means something to us, you can start editing it any time. Just ping someone one #devonly on Discord for access, linking this comment.

Sounds good! Thanks.

**Comment by musikBear** [comment]
a comment on
> Make "My Home" user definable in settings #1130

Presets saved as xpf-files has path to the instrument hard-coded in the file. It does not matter for LMMS-instruments, but it does for VST-presets
`plugin="H:/LMMS/presets/VST/DSK techsynth PRO/DSK TechSynth PRO.dll"`
This is a problem when 
* migrating to a new pc
* collabs between several users

Why not have that path dynamically linked to a path in **Settings**, then this problem would be gone

**Comment by tresf** [comment]
> Presets saved as xpf-files has path to the instrument hard-coded in the file. It does not matter for LMMS-instruments, but it does for VST-presets
plugin="H:/LMMS/presets/VST/DSK techsynth PRO/DSK TechSynth PRO.dll"

The VST relative path logic is only coded for the samples directory.  Please use that instead of the presets directory.  A DLL is not a preset and shouldn't be organized as such.

**Comment by musikBear** [comment]
> The VST relative path logic is only coded for the samples directory

@tresf  You mean that VST-instruments dll-files is meant to be in the *Samples* directory?
Eg
:..\Documents\lmms\**samples**
There?
Sorry but that is not intuitive for me. 
SF2' could be regarded as a kind of 'samples', but VST-dll's files, UI-files and banks?

What is the logic behind that idea, and when (version) did implement that ?

**Comment by tresf** [comment]
I wrote it a while ago because the relatavize logic was already written for samples, scaled well to SF2 and and there was no dedicated "plugins" folder yet so we added the logic to VSTs as a stop gap.

**Comment by musikBear** [comment]
@tresf Understood! Thanks for explaining.

**Comment by VMan-2002** [comment]
i want to loop segments please

**Comment by musikBear** [comment]
@tresf -Note "humanization" #1165 is done (No PR yet) 
But maybe it should be marked 'in progress' or 'done' idk how you normally do that.
Implementation: 
https://www.youtube.com/watch?v=jlQo5lVIbEU

**Comment by tresf** [comment]
@musikBear great news, thanks for the update.  I'll reopen, assign and change to `in progress`.

**Comment by musikBear** [comment]
In respect to 
> New default shortcuts (table) formerly (Hash)1488

I want to give a heads-up:
I have used '+' and '-' in piano-roll for resp. elongating, and shorten *selected* notes, with a simple keypress. (Implements #3138)

**Comment by Spekular** [comment]
A lot of the "closed" issues under the 1.3 milestone are actually consolidated here. In order to make it easier to see what's left to do in the milestone, I've added annotations to all the items on this list that have a milestone.

**Comment by russiankumar** [comment]
#5573 enables track coloring. Can you check that box xD?

**Comment by tresf** [comment]
@russiankumar it's marked as in-progress with that PR mentioned.  Once it's merged, yes, we'll check it off, thanks!!!

**Comment by russiankumar** [comment]
> - [ ] Proposal to use >> as default playhead behavior `#3740`
> - [ ] Stop and return |<< versus "pause" default behavior `#3740` [Milestone: 1.3]

The first one (maybe the second too) has been fixed, update?

**Comment by Spekular** [comment]
Done!

**Comment by Spekular** [comment]
I've added song editor groups to this since it "seems workflow related AND won't be closed by a quick patch", and added #5726 as a sub-item (It's a bit of a weird feature and would become largely redundant if we had groups). I'm hesitant to close #735 though, so I'm leaving it open for now but don't have any objections if someone wants to close it.

**Comment by russiankumar** [comment]
> - [ ] Better track color support #1006 #1160 #1176 #2332 (in progress: #5573)

It's complete now, could you cross it off the list?

**Comment by tresf** [comment]
> It's complete now, could you cross it off the list?

Done.

**Comment by craslaw** [comment]
I've stared work on #879. Can the original issue be reopened? I am taking the time to implement resizable rubberband selections where applicable instead of just fixing the cursor.

**Comment by zonkmachine** [comment]
@craslaw sure!

**Comment by IanCaio** [comment]
> I've started work on #879. Can the original issue be reopened? I am taking the time to implement resizable rubberband selections where applicable instead of just fixing the cursor.

Maybe you should wait until #5524 is merged, as it changes the logic and method that changes the cursor during `TrackContentObjectView`s mouse events. IMO it might make it even easier to fix this small issue with the resize cursor being used, as I think it's only a matter of adding a conditional to check if there are multiple selected TCOs.

**Comment by Rossmaxx** [comment]
@tresf can you update the list. i feel that a lot more of it has been fixed.

**Comment by Spekular** [comment]
> @tresf can you update the list. i feel that a lot more of it has been fixed.

Please don't do this unless you have specific issues in mind to be added or checked off.

**Comment by Rossmaxx** [comment]
i mean just to update the check marks. it feels like he didn't update it a lot and around 80% of the issues seem to be closed.

**Comment by Spekular** [comment]
For our meta-issues the open/closed status of a child-issue does not determine whether or not the issue is resolved. Closing issues when we consolidate them lets us keep the open issue list a little more manageable. If you would go look at some of the recently consolidated issues you'd see this in action, they're marked as closed but not resolved.

This means the list is far from 80% complete and there are no updates to be made unless you can name a specific issue and the merged PR or commit that resolves said issue.

**Comment by tresf** [comment]
> @tresf can you update the list. i feel that a lot more of it has been fixed.

Sorry, if you look at the edit log, this issue is now maintained by Spekular and others.  As instructed, any specifics that need updating, let us know.  This but tracker is huge and maintaining it is a lot of work, so the more specific the better. ♥️

**Comment by Rossmaxx** [comment]
> Rename "FX Mixer" to "Mixer" Rename "FX-Mixer" to "Mixer" #3300

Hasn't this been done

**Comment by tresf** [comment]
> > Rename "FX Mixer" to "Mixer" Rename "FX-Mixer" to "Mixer" #3300
> 
> Hasn't this been done

That bug report was closed as a consolidation effort.  I think this task is still at least partially outstanding.  https://github.com/LMMS/lmms/pull/4890#issuecomment-472079876.  The rename effort was two part:
1. UI
2. Code instances

The first is "better workflow" due to the confusing Gramogram "FX -> Effects" to just plainly call it "Mixer", however AFAIK the code is a bit more tricky as there are still instances of the UI that can clash with the core "Mixer" class.

If this has all been done, the above issue (and the linked pull requests in that issue) don't seem to address it.  If another PR/commit does close it, please link.

**Comment by tresf** [comment]
> If this has all been done, the above issue (and the linked pull requests in that issue) don't seem to address it. If another PR/commit does close it, please link.

Found it, marking as done.

**Comment by musikBear** [comment]
We have forgotten to add _Blues-scale_ to the scale-selector.
This has now been asked for by a user.
We do have _Blues-chord selection_, so _mark-all-corresponding_ is a work-around until we get Blues-scale into the Scale-selection.

**Comment by zonkmachine** [comment]
> We have forgotten to add _Blues-scale_ to the scale-selector.

The scale/chord selector is not god but those scales are there. Chord/Scale are seleceted from the number of notes. This means short scales like blues and pentatonic scales show up as chords and if you would add a very large chord in there it would show up as a scale. I believe this is mentioned elsewhere in the issue tracker.

**Comment by musikBear** [comment]
No not chord-selector. What he is missing is _blues_ in this list:
![image](https://user-images.githubusercontent.com/6662066/225966699-5bda0f71-7da1-485c-af6f-82d6d8b4f94d.png)
Is that added in Latest Nightly?
As i said the work around is
![image](https://user-images.githubusercontent.com/6662066/225966976-8cfc3eef-cb07-46f3-9744-0d2509fb5759.png)
It only takes a few mins to do, but imo we should add _Blues_ to the scales

**Comment by zonkmachine** [comment]
**Chord selector. Top right, three scales visible.**

![screenshotx](https://user-images.githubusercontent.com/6368949/225989076-89cc8e2e-343f-4b19-8aa9-8500b588647b.png)

**Comment by musikBear** [comment]
> **Chord selector. Top right, three scales visible.**
> 
> ![screenshotx](https://user-images.githubusercontent.com/6368949/225989076-89cc8e2e-343f-4b19-8aa9-8500b588647b.png)

Zonk Chords has nothing to do with this _unless_ you want to use it as **workaround** for the missing **SCALE**

**Comment by zonkmachine** [comment]
> Zonk Chords has nothing to do with this _unless_ you want to use it as **workaround** for the missing **SCALE**

I'm not talking about a workaround but merely trying to point out the reason some scales aren't showing up in the right selector.

Here is the code that choose between scale/chord depending on number of notes/size.

https://github.com/LMMS/lmms/blob/2baa23ee1a45373cbe91a8ccf55e010954af922b/include/InstrumentFunctions.h#L93-L96

It's better to take this discussion to Discord if you're still not satisfied. Also, @Veratil knows more about this.

**Comment by Rossmaxx** [comment]
> Show mixer channel on each instrument (https://github.com/LMMS/lmms/issues/2563, 6411)
> Show channel assignment on Song Editor https://github.com/LMMS/lmms/issues/2563

completed via #6831

**Comment by Spekular** [comment]
I've taken the liberty of adding #6930 and #6931 under the Song Editor and Piano Roll headings respectively. They may need to be scoped down if there are disagreements over how much state to save, but saving more than we do now is hopefully uncontroversial enough that these issues won't need to be removed from the list.

**Comment by Rossmaxx** [comment]
Make the Mixer window vertical resizable MIXER - Allow Vertical Stretching To The Mixer Window #3258

Done via #6902
