### ISSUE TITLE
VST Issues

### ISSUE THREAD

**Issue by Spekular** [LMMS/lmms#5433]
Considering the amount and nature of VST issues open, I believe a meta issue is in order.

#### Enhancements
- [ ] Idea for re-establishing VST-based LMMS-preset 'pre-hear' #5039 
- [ ] VST Scan system, multiple folder selection and some other things #4907
- [ ] Preserve plugin state when VST fails to load #4850
- [ ] Embedded plugins hide UI by default #4834
- [ ] Remove "Sync VST plugins to host playback" option #4730
- [ ] VST3 Support #4715
- [ ] Custom VST Doesn't show up plugin list when a channel is clicked on. #4585
- [ ] Add error messages if VST loading failed #4447
- [ ] 64 bit VST on Linux/Wine #4103
- [ ] Add native VST support for Mac OS X (WIP) #3975
- [ ] (VeSTige) Use a few VST(i) for many tracks #3136
- [ ] opening a VST preset should not open the VST GUI #2143
- [ ] Distinguish between VSTi and VST-FX #2003
- [ ] Scanning of VST's #1837
- [ ] Add Steinberg locations to VST search paths #1808
- [ ] VST plugins on OS X (Apple) #698
- [ ] LinuxVST support #416
- [ ] Can better automation-track labels from VSTs be implemented? #415
- [ ] VST controller knob search #308

#### Bugs/Misc

- [ ] RemoteVstPlugin fails to build with with -flto #5179
- [ ] LMMS clumsily interacts with VST #4828
- [ ] CPU overload when loading a project with specific VST's #4788
- [ ] Error Loading Plugins #4619
- [ ] VeSTige and Carla plugins sometimes interpreting wrong octave on MIDI keyboard #4535
- [ ] (Suggestion) Background Process for Checking Crashes / Other LMMS Background Processes #4408
- [ ] "Stay on top" bug when project contains VST effects #4183
- [ ] VST changes preset value on load #3847
- [ ] Not loading banks (.fxb) properly #705

#### Crashes/Freezes

- [ ] RemoteVstPlugin.exe.so crashes lmms on "incompatible Qt library" #5302 ([Source](https://github.com/lukas-w/qt5-x11embed/issues/3))
- [ ] Crashes when pushing through MIDI input while cloning a Vestige TCO #5015
- [ ] All VSTs are freezing LMMS in a minute or two (Linux, master) #4885 (XEmbed only)
- [ ] VST UIs do not scale on HiDPI screens #4411

#### Specific VST issues

- [ ] High CPU usage with the Piapro Studio VST at Idle #5353
- [ ] Kontakt is buggy in LMMS (Explanation in Description) #4087
- [ ] Issue with Vestige + Helm #3918

Tried to keep this relatively organized and limited to VST-exclusive bugs.

**Comment by Spekular** [comment]
Closed all linked issues with no activity in the past year, with the exception of crashes/freezes.

**Comment by rdrpenguin04** [comment]
I noticed #4103 is not in the list; is there a reason for that?

**Comment by Spekular** [comment]
@rdrpenguin04 good catch, fixed!

**Comment by Patjac2130** [comment]
What about [](https://github.com/LMMS/lmms/issues/6183)?

**Comment by Rossmaxx** [comment]
update the tick marks pls.

**Comment by Spekular** [comment]
> update the tick marks pls.

@Rossmaxx as mentioned on the workflow meta issue, please don't bump the thread unless you have specific issues to be added or marked as done. Unless you're involved in actual LMMS development I would refrain from trying to manage the development process (6376, 6393).

**Comment by messmerd** [comment]
I've reopened all issues that were consolidated into this meta issue and marked as closed without actually being implemented. ([see this comment](https://github.com/LMMS/lmms/pull/7851#issuecomment-3621573077))
