### ISSUE TITLE
Better logging system

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#5468]
Currently, LMMS uses several functions to print logs, e.g., `printf()`, `fprintf()`, `qWarning()`, etc. It has several issues and can be improved.

- [ ] Print log into a file (#3876)
- [ ] Better and unified logging API (#5159)
- [ ] Log viewer in the GUI

Please add comments if you have any suggestions.

**Comment by thmueller64** [comment]
What do you think of the header-only version of spdlog?
https://isocpp.org/blog/2014/11/spdlog
https://github.com/gabime/spdlog

**Comment by thmueller64** [comment]
What do you think about the header-only version of spdlog?
https://isocpp.org/blog/2014/11/spdlog
https://github.com/gabime/spdlog
