### ISSUE TITLE
Add Qt 6 support

### ISSUE THREAD

**Issue by PhysSong** [LMMS/lmms#6614]
Working branch: https://github.com/LMMS/lmms/tree/qt6

As 2023-05-26 is the EOL of Qt 5.15(without subscription licenses), it's worth starting working on Qt 6 support. Since we require C++17 and has helpers for deprecated Qt features, it might be not as hard as adding Qt 5 support.

See here for more information about how to port from Qt5 to Qt6: https://doc.qt.io/qt-6/portingguide.html

I made a checklist for Qt 6 support. Please feel free to suggest something to add.

- [x] Fix build errors/deprecation warnings with Qt 6
  - [x] Fix all deprecation warnings with Qt 5.15 (#6615)
  - [x] Handle [removal of Qt X11 extras](https://doc.qt.io/qt-6/extras-changes-qt6.html#changes-to-qt-x11-extras) (Only used in X11 embedding which is disabled er #7273)
  - [x] Replace `QRegExp` with [`QRegularExpression`](https://doc.qt.io/qt-5/qregularexpression.html) (#7133)
  - [x] ~`MM_OPERATORS` confilcts with `getDefaultCtr`/`getCopyCtr`/`getMoveCtr` of `QMetaTypeInterface` for `SampleBuffer`~: Removed in #7128
  - [x] Handle removal of `QApplication::desktop`
    - [x] in `gui_templates.h`: use `QWidget`'s DPI instead(or entirely remove, if possible) (#7185)
    - [x] in `ComboBox.cpp`: use `QWidget`'s DPI instead(or entirely remove, if possible) (#7179)
  - [x] Handle signature changes of [`QAbstractNativeEventFilter::nativeEventFilter`](https://doc.qt.io/qt-6/qabstractnativeeventfilter.html#nativeEventFilter) in Qt 6 (#7254)
  - [x] Either fix [`qt5-x11embed`](https://github.com/lukas-w/qt5-x11embed) to support Qt 6 or drop XEmbed support for Qt 6 (dropped in #7273)
  - [x] Remove usage of Qt5Compat module in hydrogen import plugin (#7562)
- [x] Work around no official supports for Qt 6 on 32bit Windows (32 bit is unsupported per consensus)
- [x] Complete Qt 6 TODOs/FIXMEs
  - [x] A `QWheelEvent` may have both x and y deltas, potentially breaking `SongEditor::wheelEvent`(see https://github.com/LMMS/lmms/pull/5619#issuecomment-673919832)
- [x] Fix new bugs with Qt 6 builds, if any
  - [x] `QComboBox::activated(const QString&)` is renamed to `textActivated` in Qt 5.14, breaking signal-slot connections
- [ ] Add CI builds for Qt 6
  - [x] Windows + MSVC
  - [ ] Windows + MinGW
  - [ ] macOS
  - [ ] Linux
- [x] Check if packaging still works
  - [x] Windows
  - [x] macOS
  - [ ] Linux
- [x] Update build instructions on Wiki

**Comment by Rossmaxx** [comment]
Opened #7133 to replace `QRegExp` with `QRegularExpression`. Might wanna add to the list.

**Comment by Rossmaxx** [comment]
> MM_OPERATORS confilcts with getDefaultCtr/getCopyCtr/getMoveCtr of QMetaTypeInterface for SampleBuffer

does this still affect post the removal of `MemoryManager` and Sample refactor?

**Comment by Snowiiii** [comment]
I saw we could use Clazy to port much of the Code to Qt6, Here is the doc page: https://doc.qt.io/qt-6/porting-to-qt6-using-clazy.html, I already tried it out and it works good, This Page is also an great Resource for Porting over: https://doc.qt.io/qt-6/portingguide.html

**Comment by sakertooth** [comment]
>  MM_OPERATORS confilcts with getDefaultCtr/getCopyCtr/getMoveCtr of QMetaTypeInterface for SampleBuffer

`MemoryManager` was removed in #7128. I think we can remove this one?

**Comment by Rossmaxx** [comment]
> Handle removal of QApplication::desktop
 in gui_templates.h: use QWidget's DPI instead(or entirely remove, if possible)
 
 done via #7159 

Also, i didn't find any uses of `QApplication::desktop` in `ComboBox.cpp`

I tried to enable experimental qt6 support via a flag at https://github.com/Rossmaxx/lmms/tree/experiment-qt6 . If you want, i can open a pr, though qt6 build still fails.

**Comment by michaelgregorius** [comment]
Pull request #7179 handles the removal of `QApplication::desktop` in `ComboBox.cpp`.

**Comment by michaelgregorius** [comment]
The Linux and mingw builds fail for pull request #7179 because the packaged Qt versions are too old. `QWidget::screen` has been introduced with 5.14 and for example Ubuntu 18.04 only provides 5.9.5.

**Comment by Rossmaxx** [comment]
#7182 is now in a mergeable state. Would help if anyone from here would review it.

**Comment by michaelgregorius** [comment]
Hi @Rossmaxx,

I have checked out the branch and have run CMake as follows:
```
cmake .. -DCMAKE_INSTALL_PREFIX=../target-qt6 -DWANT_QT6=True
```

This leads to the following error with regards to ZynAddSubFx:
```
[...]
-- Configuring done (7.0s)
CMake Error at plugins/ZynAddSubFx/CMakeLists.txt:117 (target_link_libraries):
  The link interface of target "ZynAddSubFxCore" contains:

    Qt5::Widgets

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



CMake Error at plugins/ZynAddSubFx/CMakeLists.txt:186 (TARGET_LINK_LIBRARIES):
  Target "RemoteZynAddSubFx" links to:

    Qt5::Core

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.



-- Generating done (0.4s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by michaelgregorius** [comment]
I'd like to propose to create a "qt6-migration" branch in the official repository using the changes already done in #7182. That way the code could be worked on collaboratively without the need for intermediate pull requests until everything compiles/works. Once that state is reached there could then be one "official" pull request using that branch where some final "polishing" might be discussed.

**Comment by Rossmaxx** [comment]
@michaelgregorius i forgot about that one. For now, cmake configuration only works if you set `-DLMMS_MINIMAL=ON`. A bit clunky and lacks features but that's the only way for now.

**Comment by michaelgregorius** [comment]
Thanks for the info, @Rossmaxx!

**Comment by michaelgregorius** [comment]
@Rossmaxx, I have made adjustments to your branch so that it now fully compiles. Is it okay if I push the changes into your branch?

**Comment by Rossmaxx** [comment]
> Is it okay if I push the changes into your branch? 

Yes please.

**Comment by michaelgregorius** [comment]
> > Is it okay if I push the changes into your branch?
> 
> Yes please.

Ok, great! Done with commit bb4d04b5e71.

**Comment by michaelgregorius** [comment]
Here's a list of the build warnings that are currently given when building commit 684afdb7c9e from @Rossmaxx's repository: [build_warnings.zip](https://github.com/LMMS/lmms/files/15047467/build_warnings.zip).

We will need to check how to deal with the different types of warnings. If we are lucky they can be fixed without some version specific `ifdef`s.

**Comment by Rossmaxx** [comment]
> Handle signature changes of QAbstractNativeEventFilter::nativeEventFilter in Qt 6

Any ideas on what to do here?

**Comment by PhysSong** [comment]
> > Handle signature changes of QAbstractNativeEventFilter::nativeEventFilter in Qt 6
> 
> Any ideas on what to do here?

The last parameter has type of `long` on Qt 5, but it is `quintptr` on Qt 6.

**Comment by michaelgregorius** [comment]
Depending on the surrounding code this might also be solvable with a helper method that uses a type as the last parameter that's defined via a `using` depending on the Qt version used.

So similar to what was for example done for `ControlLayout.h` here: https://github.com/LMMS/lmms/pull/7182/files#diff-6e9cbb14ccab26c8ddbde9070cef9344193bb144261c3a89c42f001f327059f7

**Comment by Rossmaxx** [comment]
> Work around no official supports for Qt 6 on 32bit Windows

#7212 has gotten rid of the requirement for 32 bit qt for 64 bit windows. Check it off?

**Comment by michaelgregorius** [comment]
> I'd like to propose to create a "qt6-migration" branch in the official repository using the changes already done in #7182. That way the code could be worked on collaboratively without the need for intermediate pull requests until everything compiles/works. Once that state is reached there could then be one "official" pull request using that branch where some final "polishing" might be discussed.

For anyone interested that branch is now available at https://github.com/LMMS/lmms/tree/qt6.

**Comment by Rossmaxx** [comment]
> The last parameter has type of long on Qt 5, but it is quintptr on Qt 6.

Added to #7086

**Comment by Rossmaxx** [comment]
Current status of Qt6 builds:
Linux - works
Mac - untested (@tresf can you help pls?)
Windows MSVC - Does not build (I've been trying to get it build for quite some time but i couldn't figure out from where the issue is coming from. The error code points to my msys2 install but it shouldn't even access there)
Windows MinGW - not planned (pretty sure Qt 6 is not available there)

@DomClark I would appreciate if you could help me debug the qt6 build.

**Comment by tresf** [comment]
>  Work around no official supports for Qt 6 on 32bit Windows

If Qt has dropped support for 32-bit OSs, I feel we should also drop support for 32-bit OSs.

**Comment by tresf** [comment]
> Mac - untested (@tresf can you help pls?)

Fantastic work!  Mac tested, [works](https://github.com/LMMS/lmms/assets/6345473/558181d6-bd0f-4b03-8735-631b64aa0571).  I tested with Unfa Spoken demo track and it sounds fine.

<details>
<summary>Commands (click to expand):</summary>


```bash
brew install git cmake pkgconfig fftw libogg libvorbis lame libsndfile libsamplerate jack \
fluid-synth sdl2 libgig libsoundio stk portaudio node fltk qt glib
#                                                          ^--- changed "qt5" to "qt"
rm -rf lmms
git clone --recurse-submodules -b master https://github.com/lmms/lmms
cd lmms
git checkout qt6
export CMAKE_PREFIX_PATH=$(brew --prefix qt)
#                                        ^--- changed "qt5" to "qt"
mkdir build
cd build
cmake .. -DCMAKE_INSTALL_PREFIX=../target -DWANT_QT6=true
#                                         ^--- added flag
make -j8
./lmms
```

</details>

**Comment by Rossmaxx** [comment]
> Will sort that on master in a separate issue/PR.

Feel free to work on that qt6 branch. As of now, the plan is to do everything there and open one final PR consisting of all changes.

**Comment by tresf** [comment]
> Windows MinGW - not planned (pretty sure Qt 6 is not available there)

If we decide to keep Mingw support around, we would require a PPA for this.  There seems to be some disagreement on Discord as to whether or not this is worthwhile to keep around.  Pinging @tobydox as an FYI.

> Feel free to work [DMG generation issues] on that `qt6` branch. As of now, the plan is to do everything there and open one final PR consisting of all changes.

Sorry, this probably wasn't clear but the DMG issues are unrelated to Qt6.  Master's DMG is only 46 MB currently (should be ~100MB) , so something's been wrong on nightly for quite some time.  I'll investigate this issue and fix it directly on master.

**Comment by tresf** [comment]
> Sorry, this probably wasn't clear but the DMG issues are unrelated to Qt6

I spoke too soon, some are.  PR opened.  #7240

Also, Zyn won't load on Apple.  I've added a checklist item to the OP to track this.

**Comment by DomClark** [comment]
>@DomClark I would appreciate if you could help me debug the qt6 build.

After applying the changes from #7086, it builds successfully for me (using Qt 6.7.1 and Visual Studio 2022). I'm happy to help debug your particular configuration, but it might be better to do that on Discord so as not to clutter this issue.

**Comment by Rossmaxx** [comment]
> After applying the changes from #7086, it builds successfully for me

Forgot that that PR had a fix. Will close that PR and open a new one against the qt6 branch.

**Comment by tresf** [comment]
Apple + Zyn removed from the checklist, the issue is also present on master.
The `libsndfile` issues fixed in #7240 are also present on master, opened a new PR against master.
Will update #7240 to simplify it to only Qt6-related changes.

**Comment by Rossmaxx** [comment]
> Handle signature changes of [QAbstractNativeEventFilter::nativeEventFilter](https://doc.qt.io/qt-6/qabstractnativeeventfilter.html#nativeEventFilter) in Qt 6

done via #7254

**Comment by Rossmaxx** [comment]
> Either fix [qt5-x11embed](https://github.com/lukas-w/qt5-x11embed) to support Qt 6 or drop XEmbed support for Qt 6
I have disabled X11 embedding for now in #7273 

> Handle [removal of Qt X11 extras](https://doc.qt.io/qt-6/extras-changes-qt6.html#changes-to-qt-x11-extras)
We don't need to, since I disabled it instead along with X11 embedding.

> Work around no official supports for Qt 6 on 32bit Windows
It would be better to not use 32 bit for Qt6 anyway, 32 bit builds can still use Qt5 (but mark 32 bit as deprecated as 1.3 and remove for future version)

Another item worth adding to the original checklist is handle removal of `Qt6::Core5Compat` module used to get Hydrogen import plugin working.

**Comment by Rossmaxx** [comment]
>  QComboBox::activated(const QString&) is renamed to textActivated in Qt 5.14, breaking signal-slot connections

fixed in #7274

**Comment by tresf** [comment]
> It would be better to not use 32 bit for Qt6 anyway, 32 bit builds can still use Qt5 (but mark 32 bit as deprecated as 1.3 and remove for future version)

Potentially unpopular opinion: I would be fine dropping 32-bit OS support entirely (NOT 32-bit VST support)
* It's been nearly 14 years since hardware was 32-bit only, so any strongholds on 32-bit can just use the old version
* Steam surveys from 3 years ago showed a nearly 100% 64-bit OS usage

**Comment by Rossmaxx** [comment]
I do agree but for that 1% of users who are still using pentiums, let them have a better version with less bugs.

**Comment by Rossmaxx** [comment]
Alright i agree completely now.

**Comment by Rossmaxx** [comment]
> A QWheelEvent may have both x and y deltas, potentially breaking SongEditor::wheelEvent()

I can't wrap my head around what to do over here. Pinging @PhysSong for assistance (I'm a bit unfamiliar with qt code in that area so would rather delegate it to you)

**Comment by tresf** [comment]
> > A QWheelEvent may have both x and y deltas, potentially breaking SongEditor::wheelEvent()
> 
> I can't wrap my head around what to do over here. Pinging @PhysSong for assistance (I'm a bit unfamiliar with qt code in that area so would rather delegate it to you)

Yeah it would likely be a refactor, but I'm really not sure how breaking this is to our codebase... These days I use a trackpad with LMMS almost exclusively.  The areas that we check for mouse direction are historically up/down.  Although we may also want to support left/right explicitly, in my experience it "just works".

For example:

* ✅ The zoom slider on a trackpad already works with both scroll directions.  
* 🚫 The mixer sliders do not work with both scroll directions
* ✅ The song editor/pattern editor already works with both scroll directions.
* 🚫 The knobs do not work with both scroll directions
* ... etc

I feel like this point may be unrelated to Qt6 as a whole and better suited for general usability improvements, to the likes of:
* https://github.com/LMMS/lmms/issues/5511
* https://github.com/LMMS/lmms/pull/6700

I too would like some more context as to this Qt6 requirement @PhysSong

**Comment by tresf** [comment]
Thanks, however, it is still not clear to me the implication of this change.  I read most of #5619 and I still do not understand the implication of this change.

**Comment by michaelgregorius** [comment]
Here's a list of all classes that override `wheelEvent` and that might need to be checked:
```
include/AutomatableSlider.h
include/AutomationEditor.h
include/ComboBox.h
include/DeprecationHelper.h
include/Fader.h
include/FloatModelEditorBase.h
include/LcdFloatSpinBox.h
include/LcdSpinBox.h
include/MidiClipView.h
include/PianoRoll.h
include/SongEditor.h
include/TabWidget.h
include/TrackContainerView.h
include/TrackView.h
plugins/AudioFileProcessor/AudioFileProcessorWaveView.h
plugins/Compressor/CompressorControlDialog.h
plugins/Eq/EqCurve.h
plugins/SlicerT/SlicerTWaveform.h
plugins/Vectorscope/VectorView.h
```

The list is a slightly filtered result of `grep -rl " wheelEvent" | sort`. I have for example removed everything found in `plugins/CarlaBase`.

**Comment by FyiurAmron** [comment]
> > I do agree but for that 1% of users who are still using pentiums, let them have a better version with less bugs.
> 
> With that mentality, why not offer 32-bit Linux binaries? We can now, thanks to #7252. Egh...
> 
> Let's look at this from 1,000 feet:
> 
> * We've NEVER offered 32-bit prebuilt images for Apple
>   
>   * Apple deprecated 32-bit support 7 years ago
> * We've NEVER offered 32-bit prebuilt images for Linux
>   
>   * Until this month, our build toolchain didn't offer support for 32-bit
> * Windows 11 does not offer a 32-bit version
>   
>   * Windows 10 32-bit is end-of-life late next year
> * 99% of users across all platforms don't use 32-bit OSs as their primary machine.
> 
> The data is stacked against any notion of keeping 32-bit around; If our aim is to move forward, dropping 32-bit is a step in the right direction. Arguments against this should come with fact and data, not grandeur. <3
> 
> Lastly, keeping "support" for 32-bit in the codebase is NOT THE SAME as removing it from our downloads. There's still people compiling LMMS against PPC, but there's absolutely no expectation of it appearing in our downloads area.

Seconded. The code can be still kept 32-bit-compatible if anyone wants to put that effort in, but first-class support for almost totally obsolete technology simply drains available dev resources really quickly. Can we go with e.g. a ticket created explicitly for dropping 32-bit support or something similar? The sooner the better, IMO - TBH, while working on updating parts of LMMS, trying to maintain 32-bit-compatibility in the build process got messy really quickly. E.g. https://github.com/FyiurAmron/lmms/actions/runs/9260084064/job/25473203303 is just a real-world example of that. While 64-bit compilation finally went ahead with no problem, I'm still debugging what's exactly wrong with the 32-bit one :D

Side note: I'm mostly a Windows 7 user (sic!), but if someone would say "let's drop support for Windows 7", I wouldn't bat an eye, as long as 7 wouldn't be artificially blocked from running the executable. I often use obsolete OSes and apps, but that doesn't mean I want the core devs wasting time on supporting them instead of doing more important stuff, like fixing bugs or adding long-awaited features.

**Comment by Rossmaxx** [comment]
@michaelgregorius i got a random idea just now. Instead of disabling x11 embed, is there a way we can make it work using `Core5Compat` module, since we use it anyway? Even if it means modifying the x11embed sources, i believe @lukas-w will be willing to merge it in with correct ifdefs

**Comment by michaelgregorius** [comment]
@Rossmaxx, I have no real overview of the X11 embed implementation and `Core5Compat`. There's also the question if `Core5Compat` might be deprecated with Qt 7, i.e. how long such an implementation will carry us. I'll let people that are more knowledgeable in that area answer that question.

**Comment by Rossmaxx** [comment]
> if Core5Compat might be deprecated with Qt 7

Hopefully, we will get done with 2.0 and different frontends by the time qt 6 will reach eol. Also, i believe we will find a better solution by then. I am looking for better solution now too tbh. 

The best solution for the embedding problem which i got was, believe it or not, disabling embedding but there are some ui related backlash for that solution, that's why i didn't go that route. 

I do hope to find a more long lasting solution by the time we land qt 6 on master.

**Comment by michaelgregorius** [comment]
Ubuntu intends to remove Qt 5 for the 26.04 TLS release: https://discourse.ubuntu.com/t/removing-qt-5-from-ubuntu-before-the-release-of-26-04-lts/49296

This should be considered when working on this issue and when putting in effort to enable the code to support both versions. Perhaps the latter is not really worth it. I assume that all popular distributions that LMMS is built for already have Qt 6 packages.

**Comment by bratpeki** [comment]
I'm adding QT5 SVG support to the MSYS building (note the icons in the Spectrum Analyzer):

![Image](https://github.com/user-attachments/assets/32c4a71a-6305-4055-a707-ecc831efb22d)

This is done by adding this installation step to the MSYS build instructions:

```
pacboy -S qt5-svg:p
```

The Qt6 SVG package is available on the MSYS package repo, so @messmerd, if you can, please note in the list about that we gotta swap `qt5` for `qt6` in that line on the Wiki!

**Comment by tresf** [comment]
> I'm adding QT5 SVG support to the MSYS building (note the icons in the Spectrum Analyzer):

Thanks!  Reference: https://github.com/LMMS/lmms/wiki/Dependencies-Windows/_compare/b561a52ab5b428e714e6070842a32667751a6e38...f375ff4d5c9ec2fbc8333b02e184528724f2bb5a

**Comment by tresf** [comment]
PR has been rebased against master. 

* #7339

Closed items:
* **Wiki:** I've added a hint to `WANT_QT6`, and steps for MSYS2 and Mac.  Feel free to add others as needed.

Open items:
* **GitHub Actions:** @messmerd will soon be adding to CI.
* **QWheelEvent:** No issues observed.  We will monitor this issue, but it will not hold up merge.
* Packaging: TBD (testing needed)

**Comment by tresf** [comment]
> PR has been rebased against master.
> 

> * **QWheelEvent:** No issues observed.  We will monitor this issue, but it will not hold up merge.

Spoke too soon.  I can no longer use the trackpad for moving around the song editor.

**Comment by michaelgregorius** [comment]
@tresf, it seems that your rebase with commit https://github.com/LMMS/lmms/commit/b276c4208a37676136ed37537b4bcbb1d5d3c36c has erased or rather rewritten some history, e.g. the changes that I have made while working on this issue and branch. I remember doing a lot of work helping to get Qt6 going and now it is not visible anymore.

You can find several of my commits in https://github.com/LMMS/lmms/pull/7182/commits. With that pull request Veratil had merged these commits into [lmms:qt6](https://github.com/LMMS/lmms/tree/qt6). Now they are not present in that branch anymore though.

If you for example check commit https://github.com/LMMS/lmms/pull/7182/commits/c45647067a12bc6a0e836c4ba7c25c709a8aac1d you will find that all of the changes made to `src/core/AutomationClip.cpp` can also be found in your commit https://github.com/LMMS/lmms/commit/b276c4208a37676136ed37537b4bcbb1d5d3c36c ("Rebase against master"). Put differently: the commit makes it look like all of the changes were done by you.

Can you please reinstate history so that people get credited for their work?

**Comment by tresf** [comment]
The rebase took me hours and it's not happening again if I can help it.  If something's missing, please method it in the PR.  I specially asked about those Automation changes there and no one chimed in.  The credit will have to be a laundry list on squash and merge.   If someone wants to try to to rewind time and correct the commit history on another branch, feel free.

**Comment by FyiurAmron** [comment]
@michaelgregorius TBH, if you _really_ need that credit on the commit, there are ways to do that via git magic _without_ having to re-do the rebase etc. - simply amending the commit message with the de-facto standard trailers, see https://stackoverflow.com/questions/7442112/how-to-attribute-a-single-commit-to-multiple-developers

Note that in bare git AFAIK a single commit always has single author, so squashes e.g. always hide the real authorship inside.

@tresf would that be OK here?

**Comment by tresf** [comment]
> in bare git AFAIK a single commit always has single author, so squashes e.g. always hide the real authorship inside.

Right, but GitHub will prepared a laundry list on squash and merge.

> @tresf would that be OK here?

I'd prefer this issue isn't used for discussing PR details but to answer this question, I don't object to your magic. 😏

This issue is about viability and pointing fingers over commit history just delays progress further.  The only reason I replied to this this finger pointing nonsense (instead of marking as off-topic) is because the comment suggests that commits may actually be missing, but t.e link leads to 60 commits, which is not specific enough to I take action on.

**Comment by michaelgregorius** [comment]
> [@michaelgregorius](https://github.com/michaelgregorius) TBH, if you _really_ need that credit on the commit, there are ways to do that via git magic _without_ having to re-do the rebase etc. - simply amending the commit message with the de-facto standard trailers, see https://stackoverflow.com/questions/7442112/how-to-attribute-a-single-commit-to-multiple-developers
> 
> Note that in bare git AFAIK a single commit always has single author, so squashes e.g. always hide the real authorship inside.
> 
> [@tresf](https://github.com/tresf) would that be OK here?

To be frank I was in the process of writing a very disappointed response because @tresf's response just comes across as disrespectful of the work of others. I also put hours of work into the code and the least that could be expected is to get some credit, isn't it? But erasing everything is not okay in my book. In the current state GitHub will very likely not include me in the "laundry list" because it very likely does not know anything about my contributions anymore.

If it is possible to do it with the trailers then I would greatly appreciate if it would be done.

I do not understand the obsession with squashes and rebases that in the first place. Why not keep the original history if there are no big blunders in the commit history? In most cases it is just code changes which could just be committed as is and problems like the one we have run into would not even show up.

The same thing could have been accomplished with a simple merge instead of a botched "rebase". To me it's not even a rebase because that should have put the existing commits on top of another one.

**Comment by michaelgregorius** [comment]
> This issue is about viability and pointing fingers over commit history just delays progress further. The only reason I replied to this finger pointing nonsense (instead of marking as off-topic) is because the comment suggests that commits may actually be missing, but the link leads to 60 commits, which is not specific enough to take action on, hence my reply.

So you do not respect the work of others and it's okay for you to make it looks as if it's your work. Got it.

**Comment by tresf** [comment]
> Spoke too soon. I can no longer use the trackpad for moving around the song editor. Reopening.

Patched 10632b31ddc022639a7b941e5edc539dc63529de.

**Comment by tresf** [comment]
> GitHub Actions: @messmerd will soon be adding to CI.

@messmerd has added the MSVC Qt6 CI jobs to the PR.  They're currently failing.  He's recently obtained a Windows machine for testing so that he can fix the issues locally instead of relying on the CI, but in the meantime any help over there is appreciated.  Next is to test Linux packaging.

**Comment by a17r** [comment]
### Qt5 is now declared deprecated in Gentoo

The final release happened on 2025-05-19, which means a) we will not get it until 2026-06-19, b) any bugs discovered since last May will not be fixed and c) no bugs since 2020-12-08 that haven't also been affecting Qt6 were fixed at all.

**Comment by messmerd** [comment]
Reopening this until we have Qt6 working on all platforms.

#7339 added support for Qt6 and switched Windows MSVC builds to use Qt6, but the other platforms are still using Qt5.

**Comment by tresf** [comment]
> Reopening this until we have Qt6 working on all platforms.
> 
> [#7339](https://github.com/LMMS/lmms/pull/7339) added support for Qt6 and switched Windows MSVC builds to use Qt6, but the other platforms are still using Qt5.

Interesting perspective, I figured the codebase would be enough to close this out... Well, we have builds working now over at #8118 (https://lmms.io/download/pull-request/8118) if we can get some more rigorous testing.
